Load the libraries

In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
#reading ratings file:
r_cols=['user_id','movie_id','rating','unix_timesstamp']
ratings=pd.read_csv('ml-100k/u.data',sep='\t',encoding='latin-1',names=r_cols)

In [3]:
ratings

       user_id  movie_id  rating  unix_timesstamp
0          196       242       3        881250949
1          186       302       3        891717742
2           22       377       1        878887116
3          244        51       2        880606923
4          166       346       1        886397596
...        ...       ...     ...              ...
99995      880       476       3        880175444
99996      716       204       5        879795543
99997      276      1090       1        874795795
99998       13       225       2        882399156
99999       12       203       3        879959583

[100000 rows x 4 columns]

In [4]:
n_user=ratings.user_id.unique().shape[0]
n_items=ratings.movie_id.unique().shape[0]
print("The no.of Users:","--->",n_user," \nThe no.of items:","--->",n_items)

The no.of Users: ---> 943
The no.of items: ---> 1682

# Create pivot table for user and movie basedon ratings

In [5]:
datama=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')
datama

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#replace with nan with 0
data_matrix=datama.replace(np.nan,0)
data_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Find cosine similarity for user and item

In [7]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(data_matrix,metric='cosine')
item_similarity=pairwise_distances(data_matrix.T,metric='cosine')

In [8]:
print(user_similarity)

[[1.33226763e-15 8.33069016e-01 9.52540457e-01 ... 8.51383057e-01
  8.20492117e-01 6.01825261e-01]
 [8.33069016e-01 0.00000000e+00 8.89408675e-01 ... 8.38515222e-01
  8.27732187e-01 8.94202122e-01]
 [9.52540457e-01 8.89408675e-01 0.00000000e+00 ... 8.98757435e-01
  8.66583851e-01 9.73444131e-01]
 ...
 [8.51383057e-01 8.38515222e-01 8.98757435e-01 ... 0.00000000e+00
  8.98358201e-01 9.04880419e-01]
 [8.20492117e-01 8.27732187e-01 8.66583851e-01 ... 8.98358201e-01
  0.00000000e+00 8.17535338e-01]
 [6.01825261e-01 8.94202122e-01 9.73444131e-01 ... 9.04880419e-01
  8.17535338e-01 0.00000000e+00]]

# Using formula for user and item we are calcuating the score value

In [9]:
def predict(ratings,similarity,type='user'):
    ratings=np.array(ratings)
    similarity=np.array(similarity)
    if type=='user':
        mean_user_rating=ratings.mean(axis=1)#-->Calculating avg. row wise.
        mean_user_rating=np.array(mean_user_rating)
        rating_diff=ratings-mean_user_rating[:,np.newaxis]#--> converting into matrix as it was in the original data by using np.newaxis.
        pred=mean_user_rating[:,np.newaxis]+similarity.dot(rating_diff)/np.array([np.abs(similarity).sum(axis=1)]).T#-->Convert 1d array into column vector, rating diff(diff/ between rating and mean,similarity matrix multiplication/
    elif type=='item':
        pred=ratings.dot(similarity)/np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [10]:
user_prediction=predict(data_matrix,user_similarity,type='user')
item_prediction=predict(data_matrix,item_similarity,type='item')

### As per User based filtering ,first have to find similarity between the input user and others

In [11]:
# 1. select input user
input_item=34

In [12]:
#2. Convert the user_sim table into dataframe
item_sim_table=pd.DataFrame(item_similarity)
item_sim_table

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.220446e-16,5.976178e-01,0.669755,5.450621e-01,0.713286,0.883656,0.379021,0.518886,0.503712,0.726065,...,0.964613,1.0,1.000000,1.000000,0.964613,1.0,1.0,1.0,0.952817,0.952817
1,5.976178e-01,2.220446e-16,0.726931,4.974292e-01,0.681164,0.916437,0.616597,0.662998,0.744748,0.828918,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.921701,0.921701
2,6.697552e-01,7.269308e-01,0.000000,6.751336e-01,0.787043,0.893278,0.627079,0.799206,0.726331,0.841896,...,1.000000,1.0,1.000000,1.000000,0.967708,1.0,1.0,1.0,1.000000,0.903125
3,5.450621e-01,4.974292e-01,0.675134,1.110223e-16,0.665761,0.909692,0.510717,0.509764,0.580956,0.747439,...,1.000000,1.0,0.905978,0.905978,0.962391,1.0,1.0,1.0,0.943587,0.924782
4,7.132865e-01,6.811638e-01,0.787043,6.657605e-01,0.000000,0.962701,0.665231,0.740839,0.727552,0.944547,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.905789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1678,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1679,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1680,9.528169e-01,9.217006e-01,1.000000,9.435867e-01,1.000000,1.000000,0.948502,0.917967,0.942640,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.000000,1.000000
1681,9.528169e-01,9.217006e-01,0.903125,9.247823e-01,0.905789,1.000000,0.948502,1.000000,0.928300,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.000000

In [13]:
#3. Find similarity user for 34 using cosine table
similar_input_item=item_sim_table[input_item].sort_values(ascending=True).head(5).index
similar_input_item

Index([34, 77, 246, 1030, 794], dtype='int64')

In [14]:
#4. Convert into list
similar_input_item=list(similar_input_item)
similar_input_item

[34, 77, 246, 1030, 794]

In [15]:
#5. Using similar_input_user, can select movie id from rating table
ratings_np=ratings.values
similar_item_userid_list=[]
for sim_item in similar_input_item:
    sim=list(ratings_np[ratings_np[:,0]==sim_item,1])
    similar_item_userid_list.append(sim)

In [16]:
len(similar_item_userid_list)

5

In [17]:
#convert all the list as single
import itertools
similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))
similar_item_userid_single_list

[np.int64(312),
 np.int64(242),
 np.int64(690),
 np.int64(310),
 np.int64(259),
 np.int64(299),
 np.int64(245),
 np.int64(332),
 np.int64(329),
 np.int64(286),
 np.int64(1024),
 np.int64(324),
 np.int64(294),
 np.int64(292),
 np.int64(990),
 np.int64(289),
 np.int64(898),
 np.int64(899),
 np.int64(288),
 np.int64(991),
 np.int64(484),
 np.int64(518),
 np.int64(172),
 np.int64(474),
 np.int64(91),
 np.int64(195),
 np.int64(238),
 np.int64(168),
 np.int64(125),
 np.int64(23),
 np.int64(498),
 np.int64(431),
 np.int64(153),
 np.int64(4),
 np.int64(181),
 np.int64(179),
 np.int64(176),
 np.int64(276),
 np.int64(50),
 np.int64(265),
 np.int64(174),
 np.int64(210),
 np.int64(69),
 np.int64(405),
 np.int64(523),
 np.int64(1028),
 np.int64(52),
 np.int64(144),
 np.int64(778),
 np.int64(89),
 np.int64(483),
 np.int64(357),
 np.int64(100),
 np.int64(133),
 np.int64(201),
 np.int64(511),
 np.int64(97),
 np.int64(56),
 np.int64(268),
 np.int64(250),
 np.int64(215),
 np.int64(209),
 np.int64(127),
 np.int64(641),
 np.int64(246),
 np.int64(15),
 np.int64(175),
 np.int64(455),
 np.int64(833),
 np.int64(31),
 np.int64(252),
 np.int64(25),
 np.int64(132),
 np.int64(1),
 np.int64(154),
 np.int64(96),
 np.int64(173),
 np.int64(28),
 np.int64(519),
 np.int64(527),
 np.int64(121),
 np.int64(156),
 np.int64(199),
 np.int64(192),
 np.int64(636),
 np.int64(98),
 np.int64(191),
 np.int64(134),
 np.int64(222),
 np.int64(183),
 np.int64(42),
 np.int64(228),
 np.int64(201),
 np.int64(919),
 np.int64(416),
 np.int64(94),
 np.int64(561),
 np.int64(409),
 np.int64(665),
 np.int64(721),
 np.int64(239),
 np.int64(425),
 np.int64(1218),
 np.int64(68),
 np.int64(82),
 np.int64(8),
 np.int64(406),
 np.int64(816),
 np.int64(728),
 np.int64(184),
 np.int64(121),
 np.int64(596),
 np.int64(80),
 np.int64(423),
 np.int64(356),
 np.int64(202),
 np.int64(578),
 np.int64(98),
 np.int64(294),
 np.int64(1073),
 np.int64(215),
 np.int64(196),
 np.int64(426),
 np.int64(849),
 np.int64(99),
 np.int64(284),
 np.int64(109),
 np.int64(802),
 np.int64(17),
 np.int64(410),
 np.int64(568),
 np.int64(368),
 np.int64(100),
 np.int64(451),
 np.int64(231),
 np.int64(840),
 np.int64(385),
 np.int64(675),
 np.int64(720),
 np.int64(541),
 np.int64(469),
 np.int64(1101),
 np.int64(1),
 np.int64(588),
 np.int64(895),
 np.int64(719),
 np.int64(161),
 np.int64(236),
 np.int64(932),
 np.int64(145),
 np.int64(547),
 np.int64(29),
 np.int64(470),
 np.int64(402),
 np.int64(369),
 np.int64(289),
 np.int64(403),
 np.int64(260),
 np.int64(1222),
 np.int64(151),
 np.int64(83),
 np.int64(195),
 np.int64(585),
 np.int64(230),
 np.int64(117),
 np.int64(628),
 np.int64(55),
 np.int64(790),
 np.int64(3),
 np.int64(232),
 np.int64(930),
 np.int64(176),
 np.int64(743),
 np.int64(265),
 np.int64(1232),
 np.int64(101),
 np.int64(831),
 np.int64(758),
 np.int64(250),
 np.int64(38),
 np.int64(444),
 np.int64(210),
 np.int64(25),
 np.int64(420),
 np.int64(41),
 np.int64(393),
 np.int64(138),
 np.int64(652),
 np.int64(211),
 np.int64(412),
 np.int64(475),
 np.int64(853),
 np.int64(238),
 np.int64(441),
 np.int64(567),
 np.int64(12),
 np.int64(208),
 np.int64(95),
 np.int64(746),
 np.int64(679),
 np.int64(24),
 np.int64(1052),
 np.int64(216),
 np.int64(77),
 np.int64(413),
 np.int64(572),
 np.int64(1411),
 np.int64(993),
 np.int64(254),
 np.int64(81),
 np.int64(118),
 np.int64(1139),
 np.int64(173),
 np.int64(92),
 np.int64(1028),
 np.int64(559),
 np.int64(198),
 np.int64(235),
 np.int64(981),
 np.int64(401),
 np.int64(1044),
 np.int64(288),
 np.int64(219),
 np.int64(132),
 np.int64(1228),
 np.int64(633),
 np.int64(97),
 np.int64(741),
 np.int64(11),
 np.int64(228),
 np.int64(576),
 np.int64(178),
 np.int64(798),
 np.int64(204),
 np.int64(431),
 np.int64(411),
 np.int64(1089),
 np.int64(748),
 np.int64(404),
 np.int64(181),
 np.int64(172),
 np.int64(672),
 np.int64(550),
 np.int64(67),
 np.int64(1188),
 np.int64(96),
 np.int64(841),
 np.int64(185),
 np.int64(809),
 np.int64(69),
 np.int64(432),
 np.int64(223),
 np.int64(570),
 np.int64(724),
 np.int64(1039),
 np.int64(174),
 np.int64(1135),
 np.int64(227),
 np.int64(133),
 np.int64(616),
 np.int64(447),
 np.int64(257),
 np.int64(941),
 np.int64(155),
 np.int64(651),
 np.int64(418),
 np.int64(50),
 np.int64(1220),
 np.int64(827),
 np.int64(252),
 np.int64(56),
 np.int64(735),
 np.int64(597),
 np.int64(111),
 np.int64(164),
 np.int64(765),
 np.int64(226),
 np.int64(433),
 np.int64(175),
 np.int64(477),
 np.int64(240),
 np.int64(658),
 np.int64(384),
 np.int64(159),
 np.int64(66),
 np.int64(739),
 np.int64(158),
 np.int64(242),
 np.int64(887),
 np.int64(118),
 np.int64(475),
 np.int64(50),
 np.int64(238),
 np.int64(514),
 np.int64(221),
 np.int64(557),
 np.int64(24),
 np.int64(847),
 np.int64(751),
 np.int64(1),
 np.int64(269),
 np.int64(248),
 np.int64(150),
 np.int64(420),
 np.int64(127),
 np.int64(275),
 np.int64(181),
 np.int64(286),
 np.int64(14),
 np.int64(116),
 np.int64(109),
 np.int64(285),
 np.int64(473),
 np.int64(224),
 np.int64(455),
 np.int64(137),
 np.int64(273),
 np.int64(13),
 np.int64(1251),
 np.int64(19),
 np.int64(257),
 np.int64(187),
 np.int64(936),
 np.int64(249),
 np.int64(515),
 np.int64(100)]

In [18]:
#7. Unique movieid from the list

Unique_userid_similar_item=set(similar_item_userid_single_list)
len(Unique_userid_similar_item)

279

In [19]:
#8. Inpute user watched move_list
input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)
input_item_watched_userid

[np.int64(286),
 np.int64(276),
 np.int64(94),
 np.int64(184),
 np.int64(1),
 np.int64(551),
 np.int64(297)]

In [20]:
#9. create a list which should have recom movieid to the input user
recom=[]
for per_id in Unique_userid_similar_item:
    if(per_id in input_item_watched_userid):
        pass
    else:
        recom.append(per_id)

In [21]:
len(recom)

274

In [22]:
sorted(recom)

[np.int64(3),
 np.int64(4),
 np.int64(8),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(17),
 np.int64(19),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(28),
 np.int64(29),
 np.int64(31),
 np.int64(38),
 np.int64(41),
 np.int64(42),
 np.int64(50),
 np.int64(52),
 np.int64(55),
 np.int64(56),
 np.int64(66),
 np.int64(67),
 np.int64(68),
 np.int64(69),
 np.int64(77),
 np.int64(80),
 np.int64(81),
 np.int64(82),
 np.int64(83),
 np.int64(89),
 np.int64(91),
 np.int64(92),
 np.int64(95),
 np.int64(96),
 np.int64(97),
 np.int64(98),
 np.int64(99),
 np.int64(100),
 np.int64(101),
 np.int64(109),
 np.int64(111),
 np.int64(116),
 np.int64(117),
 np.int64(118),
 np.int64(121),
 np.int64(125),
 np.int64(127),
 np.int64(132),
 np.int64(133),
 np.int64(134),
 np.int64(137),
 np.int64(138),
 np.int64(144),
 np.int64(145),
 np.int64(150),
 np.int64(151),
 np.int64(153),
 np.int64(154),
 np.int64(155),
 np.int64(156),
 np.int64(158),
 np.int64(159),
 np.int64(161),
 np.int64(164),
 np.int64(168),
 np.int64(172),
 np.int64(173),
 np.int64(174),
 np.int64(175),
 np.int64(176),
 np.int64(178),
 np.int64(179),
 np.int64(181),
 np.int64(183),
 np.int64(185),
 np.int64(187),
 np.int64(191),
 np.int64(192),
 np.int64(195),
 np.int64(196),
 np.int64(198),
 np.int64(199),
 np.int64(201),
 np.int64(202),
 np.int64(204),
 np.int64(208),
 np.int64(209),
 np.int64(210),
 np.int64(211),
 np.int64(215),
 np.int64(216),
 np.int64(219),
 np.int64(221),
 np.int64(222),
 np.int64(223),
 np.int64(224),
 np.int64(226),
 np.int64(227),
 np.int64(228),
 np.int64(230),
 np.int64(231),
 np.int64(232),
 np.int64(235),
 np.int64(236),
 np.int64(238),
 np.int64(239),
 np.int64(240),
 np.int64(242),
 np.int64(245),
 np.int64(246),
 np.int64(248),
 np.int64(249),
 np.int64(250),
 np.int64(252),
 np.int64(254),
 np.int64(257),
 np.int64(259),
 np.int64(260),
 np.int64(265),
 np.int64(268),
 np.int64(269),
 np.int64(273),
 np.int64(275),
 np.int64(284),
 np.int64(285),
 np.int64(288),
 np.int64(289),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(310),
 np.int64(312),
 np.int64(324),
 np.int64(329),
 np.int64(332),
 np.int64(356),
 np.int64(357),
 np.int64(368),
 np.int64(369),
 np.int64(384),
 np.int64(385),
 np.int64(393),
 np.int64(401),
 np.int64(402),
 np.int64(403),
 np.int64(404),
 np.int64(405),
 np.int64(406),
 np.int64(409),
 np.int64(410),
 np.int64(411),
 np.int64(412),
 np.int64(413),
 np.int64(416),
 np.int64(418),
 np.int64(420),
 np.int64(423),
 np.int64(425),
 np.int64(426),
 np.int64(431),
 np.int64(432),
 np.int64(433),
 np.int64(441),
 np.int64(444),
 np.int64(447),
 np.int64(451),
 np.int64(455),
 np.int64(469),
 np.int64(470),
 np.int64(473),
 np.int64(474),
 np.int64(475),
 np.int64(477),
 np.int64(483),
 np.int64(484),
 np.int64(498),
 np.int64(511),
 np.int64(514),
 np.int64(515),
 np.int64(518),
 np.int64(519),
 np.int64(523),
 np.int64(527),
 np.int64(541),
 np.int64(547),
 np.int64(550),
 np.int64(557),
 np.int64(559),
 np.int64(561),
 np.int64(567),
 np.int64(568),
 np.int64(570),
 np.int64(572),
 np.int64(576),
 np.int64(578),
 np.int64(585),
 np.int64(588),
 np.int64(596),
 np.int64(597),
 np.int64(616),
 np.int64(628),
 np.int64(633),
 np.int64(636),
 np.int64(641),
 np.int64(651),
 np.int64(652),
 np.int64(658),
 np.int64(665),
 np.int64(672),
 np.int64(675),
 np.int64(679),
 np.int64(690),
 np.int64(719),
 np.int64(720),
 np.int64(721),
 np.int64(724),
 np.int64(728),
 np.int64(735),
 np.int64(739),
 np.int64(741),
 np.int64(743),
 np.int64(746),
 np.int64(748),
 np.int64(751),
 np.int64(758),
 np.int64(765),
 np.int64(778),
 np.int64(790),
 np.int64(798),
 np.int64(802),
 np.int64(809),
 np.int64(816),
 np.int64(827),
 np.int64(831),
 np.int64(833),
 np.int64(840),
 np.int64(841),
 np.int64(847),
 np.int64(849),
 np.int64(853),
 np.int64(887),
 np.int64(895),
 np.int64(898),
 np.int64(899),
 np.int64(919),
 np.int64(930),
 np.int64(932),
 np.int64(936),
 np.int64(941),
 np.int64(981),
 np.int64(990),
 np.int64(991),
 np.int64(993),
 np.int64(1024),
 np.int64(1028),
 np.int64(1039),
 np.int64(1044),
 np.int64(1052),
 np.int64(1073),
 np.int64(1089),
 np.int64(1101),
 np.int64(1135),
 np.int64(1139),
 np.int64(1188),
 np.int64(1218),
 np.int64(1220),
 np.int64(1222),
 np.int64(1228),
 np.int64(1232),
 np.int64(1251),
 np.int64(1411)]

In [23]:
# cross checking
sorted(Unique_userid_similar_item)

[np.int64(1),
 np.int64(3),
 np.int64(4),
 np.int64(8),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(17),
 np.int64(19),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(28),
 np.int64(29),
 np.int64(31),
 np.int64(38),
 np.int64(41),
 np.int64(42),
 np.int64(50),
 np.int64(52),
 np.int64(55),
 np.int64(56),
 np.int64(66),
 np.int64(67),
 np.int64(68),
 np.int64(69),
 np.int64(77),
 np.int64(80),
 np.int64(81),
 np.int64(82),
 np.int64(83),
 np.int64(89),
 np.int64(91),
 np.int64(92),
 np.int64(94),
 np.int64(95),
 np.int64(96),
 np.int64(97),
 np.int64(98),
 np.int64(99),
 np.int64(100),
 np.int64(101),
 np.int64(109),
 np.int64(111),
 np.int64(116),
 np.int64(117),
 np.int64(118),
 np.int64(121),
 np.int64(125),
 np.int64(127),
 np.int64(132),
 np.int64(133),
 np.int64(134),
 np.int64(137),
 np.int64(138),
 np.int64(144),
 np.int64(145),
 np.int64(150),
 np.int64(151),
 np.int64(153),
 np.int64(154),
 np.int64(155),
 np.int64(156),
 np.int64(158),
 np.int64(159),
 np.int64(161),
 np.int64(164),
 np.int64(168),
 np.int64(172),
 np.int64(173),
 np.int64(174),
 np.int64(175),
 np.int64(176),
 np.int64(178),
 np.int64(179),
 np.int64(181),
 np.int64(183),
 np.int64(184),
 np.int64(185),
 np.int64(187),
 np.int64(191),
 np.int64(192),
 np.int64(195),
 np.int64(196),
 np.int64(198),
 np.int64(199),
 np.int64(201),
 np.int64(202),
 np.int64(204),
 np.int64(208),
 np.int64(209),
 np.int64(210),
 np.int64(211),
 np.int64(215),
 np.int64(216),
 np.int64(219),
 np.int64(221),
 np.int64(222),
 np.int64(223),
 np.int64(224),
 np.int64(226),
 np.int64(227),
 np.int64(228),
 np.int64(230),
 np.int64(231),
 np.int64(232),
 np.int64(235),
 np.int64(236),
 np.int64(238),
 np.int64(239),
 np.int64(240),
 np.int64(242),
 np.int64(245),
 np.int64(246),
 np.int64(248),
 np.int64(249),
 np.int64(250),
 np.int64(252),
 np.int64(254),
 np.int64(257),
 np.int64(259),
 np.int64(260),
 np.int64(265),
 np.int64(268),
 np.int64(269),
 np.int64(273),
 np.int64(275),
 np.int64(276),
 np.int64(284),
 np.int64(285),
 np.int64(286),
 np.int64(288),
 np.int64(289),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(310),
 np.int64(312),
 np.int64(324),
 np.int64(329),
 np.int64(332),
 np.int64(356),
 np.int64(357),
 np.int64(368),
 np.int64(369),
 np.int64(384),
 np.int64(385),
 np.int64(393),
 np.int64(401),
 np.int64(402),
 np.int64(403),
 np.int64(404),
 np.int64(405),
 np.int64(406),
 np.int64(409),
 np.int64(410),
 np.int64(411),
 np.int64(412),
 np.int64(413),
 np.int64(416),
 np.int64(418),
 np.int64(420),
 np.int64(423),
 np.int64(425),
 np.int64(426),
 np.int64(431),
 np.int64(432),
 np.int64(433),
 np.int64(441),
 np.int64(444),
 np.int64(447),
 np.int64(451),
 np.int64(455),
 np.int64(469),
 np.int64(470),
 np.int64(473),
 np.int64(474),
 np.int64(475),
 np.int64(477),
 np.int64(483),
 np.int64(484),
 np.int64(498),
 np.int64(511),
 np.int64(514),
 np.int64(515),
 np.int64(518),
 np.int64(519),
 np.int64(523),
 np.int64(527),
 np.int64(541),
 np.int64(547),
 np.int64(550),
 np.int64(557),
 np.int64(559),
 np.int64(561),
 np.int64(567),
 np.int64(568),
 np.int64(570),
 np.int64(572),
 np.int64(576),
 np.int64(578),
 np.int64(585),
 np.int64(588),
 np.int64(596),
 np.int64(597),
 np.int64(616),
 np.int64(628),
 np.int64(633),
 np.int64(636),
 np.int64(641),
 np.int64(651),
 np.int64(652),
 np.int64(658),
 np.int64(665),
 np.int64(672),
 np.int64(675),
 np.int64(679),
 np.int64(690),
 np.int64(719),
 np.int64(720),
 np.int64(721),
 np.int64(724),
 np.int64(728),
 np.int64(735),
 np.int64(739),
 np.int64(741),
 np.int64(743),
 np.int64(746),
 np.int64(748),
 np.int64(751),
 np.int64(758),
 np.int64(765),
 np.int64(778),
 np.int64(790),
 np.int64(798),
 np.int64(802),
 np.int64(809),
 np.int64(816),
 np.int64(827),
 np.int64(831),
 np.int64(833),
 np.int64(840),
 np.int64(841),
 np.int64(847),
 np.int64(849),
 np.int64(853),
 np.int64(887),
 np.int64(895),
 np.int64(898),
 np.int64(899),
 np.int64(919),
 np.int64(930),
 np.int64(932),
 np.int64(936),
 np.int64(941),
 np.int64(981),
 np.int64(990),
 np.int64(991),
 np.int64(993),
 np.int64(1024),
 np.int64(1028),
 np.int64(1039),
 np.int64(1044),
 np.int64(1052),
 np.int64(1073),
 np.int64(1089),
 np.int64(1101),
 np.int64(1135),
 np.int64(1139),
 np.int64(1188),
 np.int64(1218),
 np.int64(1220),
 np.int64(1222),
 np.int64(1228),
 np.int64(1232),
 np.int64(1251),
 np.int64(1411)]

In [24]:
# Cross Checking
sorted(Unique_userid_similar_item)

[np.int64(1),
 np.int64(3),
 np.int64(4),
 np.int64(8),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(17),
 np.int64(19),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(28),
 np.int64(29),
 np.int64(31),
 np.int64(38),
 np.int64(41),
 np.int64(42),
 np.int64(50),
 np.int64(52),
 np.int64(55),
 np.int64(56),
 np.int64(66),
 np.int64(67),
 np.int64(68),
 np.int64(69),
 np.int64(77),
 np.int64(80),
 np.int64(81),
 np.int64(82),
 np.int64(83),
 np.int64(89),
 np.int64(91),
 np.int64(92),
 np.int64(94),
 np.int64(95),
 np.int64(96),
 np.int64(97),
 np.int64(98),
 np.int64(99),
 np.int64(100),
 np.int64(101),
 np.int64(109),
 np.int64(111),
 np.int64(116),
 np.int64(117),
 np.int64(118),
 np.int64(121),
 np.int64(125),
 np.int64(127),
 np.int64(132),
 np.int64(133),
 np.int64(134),
 np.int64(137),
 np.int64(138),
 np.int64(144),
 np.int64(145),
 np.int64(150),
 np.int64(151),
 np.int64(153),
 np.int64(154),
 np.int64(155),
 np.int64(156),
 np.int64(158),
 np.int64(159),
 np.int64(161),
 np.int64(164),
 np.int64(168),
 np.int64(172),
 np.int64(173),
 np.int64(174),
 np.int64(175),
 np.int64(176),
 np.int64(178),
 np.int64(179),
 np.int64(181),
 np.int64(183),
 np.int64(184),
 np.int64(185),
 np.int64(187),
 np.int64(191),
 np.int64(192),
 np.int64(195),
 np.int64(196),
 np.int64(198),
 np.int64(199),
 np.int64(201),
 np.int64(202),
 np.int64(204),
 np.int64(208),
 np.int64(209),
 np.int64(210),
 np.int64(211),
 np.int64(215),
 np.int64(216),
 np.int64(219),
 np.int64(221),
 np.int64(222),
 np.int64(223),
 np.int64(224),
 np.int64(226),
 np.int64(227),
 np.int64(228),
 np.int64(230),
 np.int64(231),
 np.int64(232),
 np.int64(235),
 np.int64(236),
 np.int64(238),
 np.int64(239),
 np.int64(240),
 np.int64(242),
 np.int64(245),
 np.int64(246),
 np.int64(248),
 np.int64(249),
 np.int64(250),
 np.int64(252),
 np.int64(254),
 np.int64(257),
 np.int64(259),
 np.int64(260),
 np.int64(265),
 np.int64(268),
 np.int64(269),
 np.int64(273),
 np.int64(275),
 np.int64(276),
 np.int64(284),
 np.int64(285),
 np.int64(286),
 np.int64(288),
 np.int64(289),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(310),
 np.int64(312),
 np.int64(324),
 np.int64(329),
 np.int64(332),
 np.int64(356),
 np.int64(357),
 np.int64(368),
 np.int64(369),
 np.int64(384),
 np.int64(385),
 np.int64(393),
 np.int64(401),
 np.int64(402),
 np.int64(403),
 np.int64(404),
 np.int64(405),
 np.int64(406),
 np.int64(409),
 np.int64(410),
 np.int64(411),
 np.int64(412),
 np.int64(413),
 np.int64(416),
 np.int64(418),
 np.int64(420),
 np.int64(423),
 np.int64(425),
 np.int64(426),
 np.int64(431),
 np.int64(432),
 np.int64(433),
 np.int64(441),
 np.int64(444),
 np.int64(447),
 np.int64(451),
 np.int64(455),
 np.int64(469),
 np.int64(470),
 np.int64(473),
 np.int64(474),
 np.int64(475),
 np.int64(477),
 np.int64(483),
 np.int64(484),
 np.int64(498),
 np.int64(511),
 np.int64(514),
 np.int64(515),
 np.int64(518),
 np.int64(519),
 np.int64(523),
 np.int64(527),
 np.int64(541),
 np.int64(547),
 np.int64(550),
 np.int64(557),
 np.int64(559),
 np.int64(561),
 np.int64(567),
 np.int64(568),
 np.int64(570),
 np.int64(572),
 np.int64(576),
 np.int64(578),
 np.int64(585),
 np.int64(588),
 np.int64(596),
 np.int64(597),
 np.int64(616),
 np.int64(628),
 np.int64(633),
 np.int64(636),
 np.int64(641),
 np.int64(651),
 np.int64(652),
 np.int64(658),
 np.int64(665),
 np.int64(672),
 np.int64(675),
 np.int64(679),
 np.int64(690),
 np.int64(719),
 np.int64(720),
 np.int64(721),
 np.int64(724),
 np.int64(728),
 np.int64(735),
 np.int64(739),
 np.int64(741),
 np.int64(743),
 np.int64(746),
 np.int64(748),
 np.int64(751),
 np.int64(758),
 np.int64(765),
 np.int64(778),
 np.int64(790),
 np.int64(798),
 np.int64(802),
 np.int64(809),
 np.int64(816),
 np.int64(827),
 np.int64(831),
 np.int64(833),
 np.int64(840),
 np.int64(841),
 np.int64(847),
 np.int64(849),
 np.int64(853),
 np.int64(887),
 np.int64(895),
 np.int64(898),
 np.int64(899),
 np.int64(919),
 np.int64(930),
 np.int64(932),
 np.int64(936),
 np.int64(941),
 np.int64(981),
 np.int64(990),
 np.int64(991),
 np.int64(993),
 np.int64(1024),
 np.int64(1028),
 np.int64(1039),
 np.int64(1044),
 np.int64(1052),
 np.int64(1073),
 np.int64(1089),
 np.int64(1101),
 np.int64(1135),
 np.int64(1139),
 np.int64(1188),
 np.int64(1218),
 np.int64(1220),
 np.int64(1222),
 np.int64(1228),
 np.int64(1232),
 np.int64(1251),
 np.int64(1411)]

In [25]:
#cross checking
sorted(input_item_watched_userid)

[np.int64(1),
 np.int64(94),
 np.int64(184),
 np.int64(276),
 np.int64(286),
 np.int64(297),
 np.int64(551)]

In [26]:
# Checking the common movie list
list(set(Unique_userid_similar_item)&set(input_item_watched_userid))

[np.int64(1), np.int64(276), np.int64(184), np.int64(94), np.int64(286)]

In [27]:
item_pred=pd.DataFrame(item_prediction)
item_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.446278,0.475473,0.505938,0.443633,0.512667,0.547939,0.446243,0.463059,0.474916,0.515821,...,0.580579,0.576202,0.582478,0.582478,0.575717,0.588155,0.588155,0.588155,0.573107,0.566696
1,0.108544,0.132957,0.125589,0.124932,0.131178,0.129005,0.110883,0.122223,0.109599,0.121525,...,0.135490,0.136546,0.134829,0.134829,0.134108,0.134458,0.134458,0.134458,0.136576,0.137111
2,0.085685,0.091690,0.087643,0.089966,0.089658,0.089985,0.083492,0.089725,0.085188,0.088331,...,0.089770,0.090506,0.086261,0.086261,0.089201,0.084659,0.084659,0.084659,0.089768,0.090845
3,0.053693,0.059604,0.058114,0.058364,0.059356,0.061472,0.053374,0.058615,0.055905,0.060601,...,0.061349,0.061686,0.061195,0.061195,0.060693,0.057937,0.057937,0.057937,0.061673,0.062281
4,0.224739,0.229171,0.263280,0.226387,0.259973,0.296529,0.232710,0.237109,0.258581,0.275076,...,0.297628,0.295990,0.299922,0.299922,0.298188,0.302051,0.302051,0.302051,0.293373,0.294309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.092574,0.113870,0.110211,0.112040,0.112768,0.123140,0.098578,0.110839,0.098858,0.118579,...,0.123829,0.124430,0.120776,0.120776,0.121360,0.125056,0.125056,0.125056,0.123470,0.124327
939,0.164358,0.184894,0.196502,0.164884,0.195860,0.209652,0.162840,0.165606,0.171761,0.194536,...,0.217536,0.215515,0.219136,0.219136,0.216173,0.218583,0.218583,0.218583,0.216582,0.216819
940,0.032300,0.045024,0.042924,0.043223,0.047493,0.051077,0.032761,0.042646,0.039399,0.047421,...,0.052762,0.053042,0.052692,0.052692,0.051514,0.053028,0.053028,0.053028,0.051910,0.052280
941,0.157779,0.174095,0.189000,0.163514,0.186140,0.194151,0.164910,0.156970,0.167038,0.181295,...,0.197537,0.194479,0.198479,0.198479,0.197969,0.199793,0.199793,0.199793,0.197394,0.200031
942,0.247672,0.244892,0.282630,0.241440,0.279338,0.335121,0.250015,0.263325,0.273579,0.313885,...,0.336816,0.338652,0.338585,0.338585,0.336956,0.344104,0.344104,0.344104,0.330514,0.331025

In [28]:
item_pred[input_item]

0      0.572414
1      0.139686
2      0.092378
3      0.062496
4      0.286815
         ...
938    0.122120
939    0.217996
940    0.053046
941    0.198270
942    0.332126
Name: 34, Length: 943, dtype: float64

In [29]:
# Select the highest-rated films from the recommendation list
# based on the user's predicted ratings

highest_Rated = []

# Convert predictions into a Series indexed by movie IDs
input_item_pred = pd.Series(item_pred[input_item], index=item_pred.index)

# Iterate through recommended movies
for movie_id in recom:
    if movie_id in input_item_pred.index:
        predicted_rating = input_item_pred.loc[movie_id]
        if predicted_rating >= 1:
            highest_Rated.append(movie_id)

In [30]:
len(highest_Rated)

2

In [31]:
# checking the common movie_list
list(set(recom)&set(input_item_watched_userid))

[]

In [32]:
#Now we give movieid respective movie list

i_cols=['movie id','movie title','release date','video release date','IMDB URL','unknown','Action','Adventure','Animation',
'Children\'s','Comedy','Crime','Documentry','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']
items=pd.read_csv('ml-100k/u.item',sep='|',names=i_cols,encoding='latin-1')

In [33]:
#Creating movie list based on recom movieid
movie_title=[]
for movieid in highest_Rated:
    mov=items[items['movie id']==movieid]['movie title'].values
    movie_title.append(mov)

In [34]:
movie_title

[array(['Usual Suspects, The (1995)'], dtype=object),
 array(['Sense and Sensibility (1995)'], dtype=object)]

In [35]:
#Converting into pure list
movie_title_list=[]
for m in movie_title:
    print(m)
    mv=list(m)
    movie_title_list.append(mv)

['Usual Suspects, The (1995)']
['Sense and Sensibility (1995)']

In [36]:
#Converting into whole list
import itertools
Final_Recommend_movie=list(itertools.chain.from_iterable(movie_title_list))

In [37]:
Final_Recommend_movie

['Usual Suspects, The (1995)', 'Sense and Sensibility (1995)']

In [38]:
def itembased(input_item,item_similarity,item_predictions,similar_item_count,thres):
    #Convert the user_sim table into DataFrame
    item_sim_table=pd.DataFrame(item_similarity)
    #Find similarity user for 78 using cosine table
    similar_input_item= item_sim_table[input_item].sort_values(ascending=True).head(similar_item_count).index
    #Convert in to list
    similar_item_input=list(similar_input_item) 
    #Using similar_user_input,can select movie id from ratings table
    similar_item_userid_list=[]
    for sim_item in similar_item_input:
        sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
        similar_item_userid_list.append(sim)
    #Converting as a whole list
    import itertools
    similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))
    #Unique movieid from the list
    Unique_userid_similar_item=set(similar_item_userid_single_list)
    #Input user watched movie_list
    input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)
    #Create a list which should have recom movieid to the input user
    recom=[]
    for per_id in Unique_userid_similar_item:
        if(per_id in input_item_watched_userid):
            pass
        else:
            recom.append(per_id)
    #From recommendation list selecting only hightest rated(predicted) value
    highest_Rated=[]
    user_pred=pd.DataFrame(item_prediction)
    input_item_pre=pd.DataFrame(user_pred[input_item])
    input_item_pred=input_item_pre.T
    for re in recom:
        value=input_item_pred[re].values
        if(value>=thres):
            highest_Rated.append(re)
    highest_Rated
    return highest_Rated

In [39]:
#def userbased(input_user, user_similarity,User_predictions,similar_user_count,similar_user_movieid_count,thres):
Recommended_user=itembased(5,item_similarity,item_pred,5,0.8)

In [40]:
len(Recommended_user)

1

In [41]:
Recommended_user

[449]