Load the libraries

In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
#reading ratings file:
r_cols=['user_id','movie_id','rating','unix_timesstamp']
ratings=pd.read_csv('ml-100k/u.data',sep='\t',encoding='latin-1',names=r_cols)

In [3]:
ratings

       user_id  movie_id  rating  unix_timesstamp
0          196       242       3        881250949
1          186       302       3        891717742
2           22       377       1        878887116
3          244        51       2        880606923
4          166       346       1        886397596
...        ...       ...     ...              ...
99995      880       476       3        880175444
99996      716       204       5        879795543
99997      276      1090       1        874795795
99998       13       225       2        882399156
99999       12       203       3        879959583

[100000 rows x 4 columns]

In [4]:
n_user=ratings.user_id.unique().shape[0]
n_items=ratings.movie_id.unique().shape[0]
print("The no.of Users:","--->",n_user," \nThe no.of items:","--->",n_items)

The no.of Users: ---> 943
The no.of items: ---> 1682

# Create pivot table for user and movie basedon ratings

In [5]:
datama=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')
datama

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#replace with nan with 0
data_matrix=datama.replace(np.nan,0)
data_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Find cosine similarity for user and item

In [7]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(data_matrix,metric='cosine')
item_similarity=pairwise_distances(data_matrix.T,metric='cosine')

In [8]:
print(user_similarity)

[[1.33226763e-15 8.33069016e-01 9.52540457e-01 ... 8.51383057e-01
  8.20492117e-01 6.01825261e-01]
 [8.33069016e-01 0.00000000e+00 8.89408675e-01 ... 8.38515222e-01
  8.27732187e-01 8.94202122e-01]
 [9.52540457e-01 8.89408675e-01 0.00000000e+00 ... 8.98757435e-01
  8.66583851e-01 9.73444131e-01]
 ...
 [8.51383057e-01 8.38515222e-01 8.98757435e-01 ... 0.00000000e+00
  8.98358201e-01 9.04880419e-01]
 [8.20492117e-01 8.27732187e-01 8.66583851e-01 ... 8.98358201e-01
  0.00000000e+00 8.17535338e-01]
 [6.01825261e-01 8.94202122e-01 9.73444131e-01 ... 9.04880419e-01
  8.17535338e-01 0.00000000e+00]]

# Using formula for user and item we are calcuating the score value

In [9]:
def predict(ratings,similarity,type='user'):
    ratings=np.array(ratings)
    similarity=np.array(similarity)
    if type=='user':
        mean_user_rating=ratings.mean(axis=1)#-->Calculating avg. row wise.
        mean_user_rating=np.array(mean_user_rating)
        rating_diff=ratings-mean_user_rating[:,np.newaxis]#--> converting into matrix as it was in the original data by using np.newaxis.
        pred=mean_user_rating[:,np.newaxis]+similarity.dot(rating_diff)/np.array([np.abs(similarity).sum(axis=1)]).T#-->Convert 1d array into column vector, rating diff(diff/ between rating and mean,similarity matrix multiplication/
    elif type=='item':
        pred=ratings.dot(similarity)/np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [10]:
user_prediction=predict(data_matrix,user_similarity,type='user')
item_prediction=predict(data_matrix,item_similarity,type='item')

### As per User based filtering ,first have to find similarity between the input user and others

In [11]:
# 1. select input user
input_user=34

In [12]:
#2. Convert the user_sim table into dataframe
user_sim_table=pd.DataFrame(user_similarity)
user_sim_table

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,1.332268e-15,0.833069,0.952540,0.935642,0.621525,0.569761,0.559633,0.680928,0.921862,0.623456,...,0.630473,0.880518,0.725124,0.810295,0.802674,0.881905,0.685928,0.851383,0.820492,0.601825
1,8.330690e-01,0.000000,0.889409,0.821879,0.927021,0.754157,0.892672,0.896656,0.838952,0.840138,...,0.843014,0.692058,0.641211,0.575954,0.680111,0.771417,0.773210,0.838515,0.827732,0.894202
2,9.525405e-01,0.889409,0.000000,0.655849,0.978755,0.927585,0.933863,0.916940,0.938960,0.934849,...,0.968125,0.957247,0.836171,0.930962,0.875755,0.973729,0.838110,0.898757,0.866584,0.973444
3,9.356422e-01,0.821879,0.655849,0.000000,0.968196,0.931956,0.908770,0.811940,0.898716,0.939141,...,0.947893,0.963216,0.866885,0.806529,0.853942,0.969862,0.803142,0.847959,0.829914,0.941248
4,6.215248e-01,0.927021,0.978755,0.968196,0.000000,0.762714,0.626400,0.751070,0.943153,0.798573,...,0.661206,0.919420,0.905076,0.920221,0.851393,0.928541,0.760045,0.860405,0.847503,0.686059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,8.819047e-01,0.771417,0.973729,0.969862,0.928541,0.888148,0.892973,0.904102,0.960148,0.928540,...,0.933961,0.568846,0.741979,0.773551,0.567334,0.000000,0.912313,0.819971,0.956736,0.855750
939,6.859280e-01,0.773210,0.838110,0.803142,0.760045,0.647551,0.670075,0.753117,0.879505,0.657039,...,0.672847,0.892976,0.812464,0.818683,0.824842,0.912313,0.000000,0.854848,0.738624,0.758972
940,8.513831e-01,0.838515,0.898757,0.847959,0.860405,0.855554,0.940007,0.853855,0.856755,0.909695,...,0.953048,0.796699,0.711682,0.765789,0.686600,0.819971,0.854848,0.000000,0.898358,0.904880
941,8.204921e-01,0.827732,0.866584,0.829914,0.847503,0.682672,0.717997,0.824678,0.907503,0.787670,...,0.773560,0.926487,0.910412,0.870446,0.900615,0.956736,0.738624,0.898358,0.000000,0.817535
942,6.018253e-01,0.894202,0.973444,0.941248,0.686059,0.723958,0.605636,0.700191,0.924383,0.778140,...,0.736209,0.789237,0.856747,0.922207,0.797756,0.855750,0.758972,0.904880,0.817535,0.000000

In [13]:
#3. Find similarity user for 34 using cosine table
similar_input_user=user_sim_table[input_user].sort_values(ascending=True).head(5).index
similar_input_user

Index([34, 450, 852, 811, 509], dtype='int64')

In [14]:
#4. Convert into list
similar_input_user=list(similar_input_user)
similar_input_user

[34, 450, 852, 811, 509]

In [15]:
#5. Using similar_input_user, can select movie id from rating table
ratings_np=ratings.values
similar_user_movieid_list=[]
for sim_user in similar_input_user:
    sim=list(ratings_np[ratings_np[:,0]==sim_user,1])
    similar_user_movieid_list.append(sim)

In [16]:
len(similar_user_movieid_list)

5

In [17]:
similar_user_movieid_list

[[np.int64(312),
  np.int64(242),
  np.int64(690),
  np.int64(310),
  np.int64(259),
  np.int64(299),
  np.int64(245),
  np.int64(332),
  np.int64(329),
  np.int64(286),
  np.int64(1024),
  np.int64(324),
  np.int64(294),
  np.int64(292),
  np.int64(990),
  np.int64(289),
  np.int64(898),
  np.int64(899),
  np.int64(288),
  np.int64(991)],
 [np.int64(470),
  np.int64(783),
  np.int64(1147),
  np.int64(100),
  np.int64(58),
  np.int64(142),
  np.int64(801),
  np.int64(216),
  np.int64(785),
  np.int64(162),
  np.int64(144),
  np.int64(462),
  np.int64(384),
  np.int64(739),
  np.int64(1269),
  np.int64(179),
  np.int64(38),
  np.int64(659),
  np.int64(252),
  np.int64(1160),
  np.int64(566),
  np.int64(496),
  np.int64(679),
  np.int64(387),
  np.int64(908),
  np.int64(265),
  np.int64(1226),
  np.int64(183),
  np.int64(1037),
  np.int64(194),
  np.int64(902),
  np.int64(1263),
  np.int64(64),
  np.int64(1036),
  np.int64(942),
  np.int64(467),
  np.int64(1212),
  np.int64(97),
  np.int64(762),
  np.int64(143),
  np.int64(583),
  np.int64(480),
  np.int64(846),
  np.int64(561),
  np.int64(487),
  np.int64(2),
  np.int64(237),
  np.int64(39),
  np.int64(778),
  np.int64(815),
  np.int64(708),
  np.int64(400),
  np.int64(495),
  np.int64(382),
  np.int64(518),
  np.int64(110),
  np.int64(1203),
  np.int64(710),
  np.int64(660),
  np.int64(152),
  np.int64(304),
  np.int64(520),
  np.int64(604),
  np.int64(642),
  np.int64(494),
  np.int64(211),
  np.int64(847),
  np.int64(559),
  np.int64(1446),
  np.int64(204),
  np.int64(904),
  np.int64(1092),
  np.int64(281),
  np.int64(526),
  np.int64(139),
  np.int64(200),
  np.int64(367),
  np.int64(553),
  np.int64(523),
  np.int64(685),
  np.int64(478),
  np.int64(177),
  np.int64(742),
  np.int64(1044),
  np.int64(509),
  np.int64(89),
  np.int64(238),
  np.int64(29),
  np.int64(15),
  np.int64(837),
  np.int64(65),
  np.int64(49),
  np.int64(176),
  np.int64(434),
  np.int64(729),
  np.int64(1184),
  np.int64(70),
  np.int64(728),
  np.int64(174),
  np.int64(1047),
  np.int64(723),
  np.int64(477),
  np.int64(419),
  np.int64(689),
  np.int64(582),
  np.int64(270),
  np.int64(7),
  np.int64(155),
  np.int64(12),
  np.int64(774),
  np.int64(383),
  np.int64(488),
  np.int64(145),
  np.int64(401),
  np.int64(301),
  np.int64(468),
  np.int64(157),
  np.int64(771),
  np.int64(650),
  np.int64(288),
  np.int64(95),
  np.int64(1),
  np.int64(154),
  np.int64(1020),
  np.int64(712),
  np.int64(227),
  np.int64(923),
  np.int64(1222),
  np.int64(1152),
  np.int64(101),
  np.int64(395),
  np.int64(1050),
  np.int64(94),
  np.int64(272),
  np.int64(629),
  np.int64(225),
  np.int64(402),
  np.int64(736),
  np.int64(707),
  np.int64(60),
  np.int64(613),
  np.int64(465),
  np.int64(747),
  np.int64(493),
  np.int64(123),
  np.int64(10),
  np.int64(514),
  np.int64(1041),
  np.int64(13),
  np.int64(451),
  np.int64(418),
  np.int64(611),
  np.int64(258),
  np.int64(905),
  np.int64(1479),
  np.int64(502),
  np.int64(792),
  np.int64(131),
  np.int64(673),
  np.int64(56),
  np.int64(940),
  np.int64(1192),
  np.int64(158),
  np.int64(203),
  np.int64(193),
  np.int64(612),
  np.int64(1054),
  np.int64(134),
  np.int64(99),
  np.int64(607),
  np.int64(127),
  np.int64(428),
  np.int64(378),
  np.int64(294),
  np.int64(469),
  np.int64(208),
  np.int64(290),
  np.int64(1030),
  np.int64(632),
  np.int64(663),
  np.int64(878),
  np.int64(132),
  np.int64(751),
  np.int64(1039),
  np.int64(967),
  np.int64(1603),
  np.int64(472),
  np.int64(474),
  np.int64(765),
  np.int64(482),
  np.int64(1261),
  np.int64(614),
  np.int64(700),
  np.int64(92),
  np.int64(928),
  np.int64(589),
  np.int64(591),
  np.int64(385),
  np.int64(282),
  np.int64(305),
  np.int64(275),
  np.int64(873),
  np.int64(195),
  np.int64(299),
  np.int64(153),
  np.int64(381),
  np.int64(231),
  np.int64(865),
  np.int64(484),
  np.int64(1033),
  np.int64(199),
  np.int64(311),
  np.int64(433),
  np.int64(1140),
  np.int64(315),
  np.int64(790),
  np.int64(371),
  np.int64(357),
  np.int64(1172),
  np.int64(1401),
  np.int64(354),
  np.int64(54),
  np.int64(558),
  np.int64(241),
  np.int64(1402),
  np.int64(207),
  np.int64(550),
  np.int64(637),
  np.int64(414),
  np.int64(340),
  np.int64(506),
  np.int64(313),
  np.int64(1221),
  np.int64(283),
  np.int64(692),
  np.int64(80),
  np.int64(66),
  np.int64(222),
  np.int64(647),
  np.int64(192),
  np.int64(549),
  np.int64(136),
  np.int64(610),
  np.int64(35),
  np.int64(507),
  np.int64(490),
  np.int64(510),
  np.int64(164),
  np.int64(135),
  np.int64(735),
  np.int64(245),
  np.int64(842),
  np.int64(714),
  np.int64(4),
  np.int64(302),
  np.int64(121),
  np.int64(430),
  np.int64(1425),
  np.int64(686),
  np.int64(775),
  np.int64(312),
  np.int64(205),
  np.int64(81),
  np.int64(1286),
  np.int64(525),
  np.int64(77),
  np.int64(921),
  np.int64(1048),
  np.int64(965),
  np.int64(26),
  np.int64(651),
  np.int64(934),
  np.int64(1444),
  np.int64(71),
  np.int64(98),
  np.int64(233),
  np.int64(141),
  np.int64(956),
  np.int64(491),
  np.int64(185),
  np.int64(448),
  np.int64(169),
  np.int64(1441),
  np.int64(1153),
  np.int64(328),
  np.int64(421),
  np.int64(182),
  np.int64(163),
  np.int64(83),
  np.int64(187),
  np.int64(661),
  np.int64(471),
  np.int64(239),
  np.int64(497),
  np.int64(264),
  np.int64(966),
  np.int64(527),
  np.int64(731),
  np.int64(823),
  np.int64(274),
  np.int64(380),
  np.int64(316),
  np.int64(166),
  np.int64(125),
  np.int64(535),
  np.int64(1208),
  np.int64(393),
  np.int64(845),
  np.int64(609),
  np.int64(1091),
  np.int64(1220),
  np.int64(1271),
  np.int64(79),
  np.int64(1116),
  np.int64(278),
  np.int64(969),
  np.int64(277),
  np.int64(1248),
  np.int64(191),
  np.int64(455),
  np.int64(197),
  np.int64(86),
  np.int64(432),
  np.int64(287),
  np.int64(807),
  np.int64(51),
  np.int64(606),
  np.int64(1435),
  np.int64(761),
  np.int64(67),
  np.int64(479),
  np.int64(705),
  np.int64(821),
  np.int64(622),
  np.int64(90),
  np.int64(709),
  np.int64(500),
  np.int64(396),
  np.int64(202),
  np.int64(530),
  np.int64(427),
  np.int64(481),
  np.int64(936),
  np.int64(73),
  np.int64(1028),
  np.int64(112),
  np.int64(503),
  np.int64(716),
  np.int64(82),
  np.int64(126),
  np.int64(373),
  np.int64(280),
  np.int64(292),
  np.int64(422),
  np.int64(869),
  np.int64(476),
  np.int64(443),
  np.int64(832),
  np.int64(226),
  np.int64(939),
  np.int64(608),
  np.int64(631),
  np.int64(167),
  np.int64(693),
  np.int64(431),
  np.int64(1521),
  np.int64(602),
  np.int64(1053),
  np.int64(648),
  np.int64(715),
  np.int64(215),
  np.int64(900),
  np.int64(254),
  np.int64(210),
  np.int64(657),
  np.int64(88),
  np.int64(117),
  np.int64(655),
  np.int64(269),
  np.int64(180),
  np.int64(1163),
  np.int64(794),
  np.int64(951),
  np.int64(568),
  np.int64(28),
  np.int64(633),
  np.int64(87),
  np.int64(1282),
  np.int64(168),
  np.int64(630),
  np.int64(1303),
  np.int64(332),
  np.int64(3),
  np.int64(717),
  np.int64(557),
  np.int64(218),
  np.int64(223),
  np.int64(499),
  np.int64(173),
  np.int64(161),
  np.int64(1119),
  np.int64(229),
  np.int64(704),
  np.int64(416),
  np.int64(417),
  np.int64(483),
  np.int64(505),
  np.int64(528),
  np.int64(570),
  np.int64(1115),
  np.int64(196),
  np.int64(133),
  np.int64(620),
  np.int64(310),
  np.int64(618),
  np.int64(300),
  np.int64(114),
  np.int64(511),
  np.int64(435),
  np.int64(748),
  np.int64(727),
  np.int64(926),
  np.int64(1284),
  np.int64(749),
  np.int64(284),
  np.int64(318),
  np.int64(968),
  np.int64(501),
  np.int64(307),
  np.int64(713),
  np.int64(188),
  np.int64(662),
  np.int64(96),
  np.int64(389),
  np.int64(50),
  np.int64(347),
  np.int64(230),
  np.int64(372),
  np.int64(181),
  np.int64(627),
  np.int64(336),
  np.int64(235),
  np.int64(190),
  np.int64(102),
  np.int64(403),
  np.int64(221),
  np.int64(23),
  np.int64(734),
  np.int64(671),
  np.int64(43),
  np.int64(172),
  np.int64(345),
  np.int64(741),
  np.int64(118),
  np.int64(386),
  np.int64(776),
  np.int64(519),
  np.int64(866),
  np.int64(33),
  np.int64(702),
  np.int64(1135),
  np.int64(485),
  np.int64(273),
  np.int64(76),
  np.int64(492),
  np.int64(750),
  np.int64(1311),
  np.int64(1249),
  np.int64(1107),
  np.int64(260),
  np.int64(1197),
  np.int64(588),
  np.int64(546),
  np.int64(392),
  np.int64(78),
  np.int64(597),
  np.int64(213),
  np.int64(489),
  np.int64(619),
  np.int64(214),
  np.int64(696),
  np.int64(220),
  np.int64(812),
  np.int64(571),
  np.int64(1297),
  np.int64(725),
  np.int64(322),
  np.int64(111),
  np.int64(286),
  np.int64(724),
  np.int64(457),
  np.int64(259),
  np.int64(44),
  np.int64(722),
  np.int64(47),
  np.int64(616),
  np.int64(91),
  np.int64(699),
  np.int64(601),
  np.int64(186),
  np.int64(603),
  np.int64(61),
  np.int64(11),
  np.int64(423),
  np.int64(781),
  np.int64(521),
  np.int64(498),
  np.int64(140),
  np.int64(151),
  np.int64(756),
  np.int64(1112),
  np.int64(59),
  np.int64(69),
  np.int64(366),
  np.int64(1518),
  np.int64(405),
  np.int64(415),
  np.int64(232),
  np.int64(504),
  np.int64(63),
  np.int64(795),
  np.int64(628),
  np.int64(22),
  np.int64(356),
  np.int64(1421),
  np.int64(25),
  np.int64(228),
  np.int64(170),
  np.int64(1126),
  np.int64(516),
  np.int64(1480),
  np.int64(1061),
  np.int64(234),
  np.int64(399),
  np.int64(178),
  np.int64(584),
  np.int64(732),
  np.int64(388),
  np.int64(1490),
  np.int64(654)],
 [np.int64(685),
  np.int64(473),
  np.int64(408),
  np.int64(323),
  np.int64(118),
  np.int64(257),
  np.int64(151),
  np.int64(546),
  np.int64(127),
  np.int64(597),
  np.int64(289),
  np.int64(820),
  np.int64(930),
  np.int64(678),
  np.int64(841),
  np.int64(515),
  np.int64(181),
  np.int64(7),
  np.int64(405),
  np.int64(260),
  np.int64(840),
  np.int64(50),
  np.int64(681),
  np.int64(274),
  np.int64(1052),
  np.int64(825),
  np.int64(969),
  np.int64(259),
  np.int64(25),
  np.int64(235),
  np.int64(1),
  np.int64(122),
  np.int64(827),
  np.int64(252),
  np.int64(358),
  np.int64(472),
  np.int64(117),
  np.int64(826),
  np.int64(121),
  np.int64(264),
  np.int64(109),
  np.int64(1615),
  np.int64(407),
  np.int64(568),
  np.int64(100),
  np.int64(506),
  np.int64(250),
  np.int64(926),
  np.int64(290)],
 [np.int64(301),
  np.int64(292),
  np.int64(304),
  np.int64(294),
  np.int64(748),
  np.int64(690),
  np.int64(258),
  np.int64(323),
  np.int64(892),
  np.int64(289),
  np.int64(307),
  np.int64(286),
  np.int64(315),
  np.int64(300),
  np.int64(308),
  np.int64(895),
  np.int64(988),
  np.int64(321),
  np.int64(678),
  np.int64(243),
  np.int64(901)],
 [np.int64(319),
  np.int64(50),
  np.int64(288),
  np.int64(680),
  np.int64(751),
  np.int64(310),
  np.int64(300),
  np.int64(260),
  np.int64(879),
  np.int64(687),
  np.int64(258),
  np.int64(603),
  np.int64(332),
  np.int64(302),
  np.int64(754),
  np.int64(289),
  np.int64(301),
  np.int64(345),
  np.int64(326),
  np.int64(307),
  np.int64(343),
  np.int64(268),
  np.int64(892),
  np.int64(338),
  np.int64(266),
  np.int64(328),
  np.int64(690),
  np.int64(245),
  np.int64(181),
  np.int64(309),
  np.int64(294),
  np.int64(271),
  np.int64(705)]]

In [18]:
#convert all the list as single
import itertools
similar_user_movieid_single_list=list(itertools.chain.from_iterable(similar_user_movieid_list))
len(similar_user_movieid_single_list)

663

In [19]:
#7. Unique movieid from the list

Unique_movieid_similar_user=set(similar_user_movieid_single_list)
len(Unique_movieid_similar_user)

590

In [20]:
#8. Inpute user watched move_list
input_user_watched_movieid=list(ratings[ratings['user_id']==input_user]['movie_id'].values)
input_user_watched_movieid

[np.int64(312),
 np.int64(242),
 np.int64(690),
 np.int64(310),
 np.int64(259),
 np.int64(299),
 np.int64(245),
 np.int64(332),
 np.int64(329),
 np.int64(286),
 np.int64(1024),
 np.int64(324),
 np.int64(294),
 np.int64(292),
 np.int64(990),
 np.int64(289),
 np.int64(898),
 np.int64(899),
 np.int64(288),
 np.int64(991)]

In [21]:
#9. create a list which should have recom movieid to the input user
recom=[]
for per_id in Unique_movieid_similar_user:
    if(per_id in input_user_watched_movieid):
        pass
    else:
        recom.append(per_id)

In [22]:
len(recom)

570

In [23]:
sorted(recom)

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(7),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(15),
 np.int64(22),
 np.int64(23),
 np.int64(25),
 np.int64(26),
 np.int64(28),
 np.int64(29),
 np.int64(33),
 np.int64(35),
 np.int64(38),
 np.int64(39),
 np.int64(43),
 np.int64(44),
 np.int64(47),
 np.int64(49),
 np.int64(50),
 np.int64(51),
 np.int64(54),
 np.int64(56),
 np.int64(58),
 np.int64(59),
 np.int64(60),
 np.int64(61),
 np.int64(63),
 np.int64(64),
 np.int64(65),
 np.int64(66),
 np.int64(67),
 np.int64(69),
 np.int64(70),
 np.int64(71),
 np.int64(73),
 np.int64(76),
 np.int64(77),
 np.int64(78),
 np.int64(79),
 np.int64(80),
 np.int64(81),
 np.int64(82),
 np.int64(83),
 np.int64(86),
 np.int64(87),
 np.int64(88),
 np.int64(89),
 np.int64(90),
 np.int64(91),
 np.int64(92),
 np.int64(94),
 np.int64(95),
 np.int64(96),
 np.int64(97),
 np.int64(98),
 np.int64(99),
 np.int64(100),
 np.int64(101),
 np.int64(102),
 np.int64(109),
 np.int64(110),
 np.int64(111),
 np.int64(112),
 np.int64(114),
 np.int64(117),
 np.int64(118),
 np.int64(121),
 np.int64(122),
 np.int64(123),
 np.int64(125),
 np.int64(126),
 np.int64(127),
 np.int64(131),
 np.int64(132),
 np.int64(133),
 np.int64(134),
 np.int64(135),
 np.int64(136),
 np.int64(139),
 np.int64(140),
 np.int64(141),
 np.int64(142),
 np.int64(143),
 np.int64(144),
 np.int64(145),
 np.int64(151),
 np.int64(152),
 np.int64(153),
 np.int64(154),
 np.int64(155),
 np.int64(157),
 np.int64(158),
 np.int64(161),
 np.int64(162),
 np.int64(163),
 np.int64(164),
 np.int64(166),
 np.int64(167),
 np.int64(168),
 np.int64(169),
 np.int64(170),
 np.int64(172),
 np.int64(173),
 np.int64(174),
 np.int64(176),
 np.int64(177),
 np.int64(178),
 np.int64(179),
 np.int64(180),
 np.int64(181),
 np.int64(182),
 np.int64(183),
 np.int64(185),
 np.int64(186),
 np.int64(187),
 np.int64(188),
 np.int64(190),
 np.int64(191),
 np.int64(192),
 np.int64(193),
 np.int64(194),
 np.int64(195),
 np.int64(196),
 np.int64(197),
 np.int64(199),
 np.int64(200),
 np.int64(202),
 np.int64(203),
 np.int64(204),
 np.int64(205),
 np.int64(207),
 np.int64(208),
 np.int64(210),
 np.int64(211),
 np.int64(213),
 np.int64(214),
 np.int64(215),
 np.int64(216),
 np.int64(218),
 np.int64(220),
 np.int64(221),
 np.int64(222),
 np.int64(223),
 np.int64(225),
 np.int64(226),
 np.int64(227),
 np.int64(228),
 np.int64(229),
 np.int64(230),
 np.int64(231),
 np.int64(232),
 np.int64(233),
 np.int64(234),
 np.int64(235),
 np.int64(237),
 np.int64(238),
 np.int64(239),
 np.int64(241),
 np.int64(243),
 np.int64(250),
 np.int64(252),
 np.int64(254),
 np.int64(257),
 np.int64(258),
 np.int64(260),
 np.int64(264),
 np.int64(265),
 np.int64(266),
 np.int64(268),
 np.int64(269),
 np.int64(270),
 np.int64(271),
 np.int64(272),
 np.int64(273),
 np.int64(274),
 np.int64(275),
 np.int64(277),
 np.int64(278),
 np.int64(280),
 np.int64(281),
 np.int64(282),
 np.int64(283),
 np.int64(284),
 np.int64(287),
 np.int64(290),
 np.int64(300),
 np.int64(301),
 np.int64(302),
 np.int64(304),
 np.int64(305),
 np.int64(307),
 np.int64(308),
 np.int64(309),
 np.int64(311),
 np.int64(313),
 np.int64(315),
 np.int64(316),
 np.int64(318),
 np.int64(319),
 np.int64(321),
 np.int64(322),
 np.int64(323),
 np.int64(326),
 np.int64(328),
 np.int64(336),
 np.int64(338),
 np.int64(340),
 np.int64(343),
 np.int64(345),
 np.int64(347),
 np.int64(354),
 np.int64(356),
 np.int64(357),
 np.int64(358),
 np.int64(366),
 np.int64(367),
 np.int64(371),
 np.int64(372),
 np.int64(373),
 np.int64(378),
 np.int64(380),
 np.int64(381),
 np.int64(382),
 np.int64(383),
 np.int64(384),
 np.int64(385),
 np.int64(386),
 np.int64(387),
 np.int64(388),
 np.int64(389),
 np.int64(392),
 np.int64(393),
 np.int64(395),
 np.int64(396),
 np.int64(399),
 np.int64(400),
 np.int64(401),
 np.int64(402),
 np.int64(403),
 np.int64(405),
 np.int64(407),
 np.int64(408),
 np.int64(414),
 np.int64(415),
 np.int64(416),
 np.int64(417),
 np.int64(418),
 np.int64(419),
 np.int64(421),
 np.int64(422),
 np.int64(423),
 np.int64(427),
 np.int64(428),
 np.int64(430),
 np.int64(431),
 np.int64(432),
 np.int64(433),
 np.int64(434),
 np.int64(435),
 np.int64(443),
 np.int64(448),
 np.int64(451),
 np.int64(455),
 np.int64(457),
 np.int64(462),
 np.int64(465),
 np.int64(467),
 np.int64(468),
 np.int64(469),
 np.int64(470),
 np.int64(471),
 np.int64(472),
 np.int64(473),
 np.int64(474),
 np.int64(476),
 np.int64(477),
 np.int64(478),
 np.int64(479),
 np.int64(480),
 np.int64(481),
 np.int64(482),
 np.int64(483),
 np.int64(484),
 np.int64(485),
 np.int64(487),
 np.int64(488),
 np.int64(489),
 np.int64(490),
 np.int64(491),
 np.int64(492),
 np.int64(493),
 np.int64(494),
 np.int64(495),
 np.int64(496),
 np.int64(497),
 np.int64(498),
 np.int64(499),
 np.int64(500),
 np.int64(501),
 np.int64(502),
 np.int64(503),
 np.int64(504),
 np.int64(505),
 np.int64(506),
 np.int64(507),
 np.int64(509),
 np.int64(510),
 np.int64(511),
 np.int64(514),
 np.int64(515),
 np.int64(516),
 np.int64(518),
 np.int64(519),
 np.int64(520),
 np.int64(521),
 np.int64(523),
 np.int64(525),
 np.int64(526),
 np.int64(527),
 np.int64(528),
 np.int64(530),
 np.int64(535),
 np.int64(546),
 np.int64(549),
 np.int64(550),
 np.int64(553),
 np.int64(557),
 np.int64(558),
 np.int64(559),
 np.int64(561),
 np.int64(566),
 np.int64(568),
 np.int64(570),
 np.int64(571),
 np.int64(582),
 np.int64(583),
 np.int64(584),
 np.int64(588),
 np.int64(589),
 np.int64(591),
 np.int64(597),
 np.int64(601),
 np.int64(602),
 np.int64(603),
 np.int64(604),
 np.int64(606),
 np.int64(607),
 np.int64(608),
 np.int64(609),
 np.int64(610),
 np.int64(611),
 np.int64(612),
 np.int64(613),
 np.int64(614),
 np.int64(616),
 np.int64(618),
 np.int64(619),
 np.int64(620),
 np.int64(622),
 np.int64(627),
 np.int64(628),
 np.int64(629),
 np.int64(630),
 np.int64(631),
 np.int64(632),
 np.int64(633),
 np.int64(637),
 np.int64(642),
 np.int64(647),
 np.int64(648),
 np.int64(650),
 np.int64(651),
 np.int64(654),
 np.int64(655),
 np.int64(657),
 np.int64(659),
 np.int64(660),
 np.int64(661),
 np.int64(662),
 np.int64(663),
 np.int64(671),
 np.int64(673),
 np.int64(678),
 np.int64(679),
 np.int64(680),
 np.int64(681),
 np.int64(685),
 np.int64(686),
 np.int64(687),
 np.int64(689),
 np.int64(692),
 np.int64(693),
 np.int64(696),
 np.int64(699),
 np.int64(700),
 np.int64(702),
 np.int64(704),
 np.int64(705),
 np.int64(707),
 np.int64(708),
 np.int64(709),
 np.int64(710),
 np.int64(712),
 np.int64(713),
 np.int64(714),
 np.int64(715),
 np.int64(716),
 np.int64(717),
 np.int64(722),
 np.int64(723),
 np.int64(724),
 np.int64(725),
 np.int64(727),
 np.int64(728),
 np.int64(729),
 np.int64(731),
 np.int64(732),
 np.int64(734),
 np.int64(735),
 np.int64(736),
 np.int64(739),
 np.int64(741),
 np.int64(742),
 np.int64(747),
 np.int64(748),
 np.int64(749),
 np.int64(750),
 np.int64(751),
 np.int64(754),
 np.int64(756),
 np.int64(761),
 np.int64(762),
 np.int64(765),
 np.int64(771),
 np.int64(774),
 np.int64(775),
 np.int64(776),
 np.int64(778),
 np.int64(781),
 np.int64(783),
 np.int64(785),
 np.int64(790),
 np.int64(792),
 np.int64(794),
 np.int64(795),
 np.int64(801),
 np.int64(807),
 np.int64(812),
 np.int64(815),
 np.int64(820),
 np.int64(821),
 np.int64(823),
 np.int64(825),
 np.int64(826),
 np.int64(827),
 np.int64(832),
 np.int64(837),
 np.int64(840),
 np.int64(841),
 np.int64(842),
 np.int64(845),
 np.int64(846),
 np.int64(847),
 np.int64(865),
 np.int64(866),
 np.int64(869),
 np.int64(873),
 np.int64(878),
 np.int64(879),
 np.int64(892),
 np.int64(895),
 np.int64(900),
 np.int64(901),
 np.int64(902),
 np.int64(904),
 np.int64(905),
 np.int64(908),
 np.int64(921),
 np.int64(923),
 np.int64(926),
 np.int64(928),
 np.int64(930),
 np.int64(934),
 np.int64(936),
 np.int64(939),
 np.int64(940),
 np.int64(942),
 np.int64(951),
 np.int64(956),
 np.int64(965),
 np.int64(966),
 np.int64(967),
 np.int64(968),
 np.int64(969),
 np.int64(988),
 np.int64(1020),
 np.int64(1028),
 np.int64(1030),
 np.int64(1033),
 np.int64(1036),
 np.int64(1037),
 np.int64(1039),
 np.int64(1041),
 np.int64(1044),
 np.int64(1047),
 np.int64(1048),
 np.int64(1050),
 np.int64(1052),
 np.int64(1053),
 np.int64(1054),
 np.int64(1061),
 np.int64(1091),
 np.int64(1092),
 np.int64(1107),
 np.int64(1112),
 np.int64(1115),
 np.int64(1116),
 np.int64(1119),
 np.int64(1126),
 np.int64(1135),
 np.int64(1140),
 np.int64(1147),
 np.int64(1152),
 np.int64(1153),
 np.int64(1160),
 np.int64(1163),
 np.int64(1172),
 np.int64(1184),
 np.int64(1192),
 np.int64(1197),
 np.int64(1203),
 np.int64(1208),
 np.int64(1212),
 np.int64(1220),
 np.int64(1221),
 np.int64(1222),
 np.int64(1226),
 np.int64(1248),
 np.int64(1249),
 np.int64(1261),
 np.int64(1263),
 np.int64(1269),
 np.int64(1271),
 np.int64(1282),
 np.int64(1284),
 np.int64(1286),
 np.int64(1297),
 np.int64(1303),
 np.int64(1311),
 np.int64(1401),
 np.int64(1402),
 np.int64(1421),
 np.int64(1425),
 np.int64(1435),
 np.int64(1441),
 np.int64(1444),
 np.int64(1446),
 np.int64(1479),
 np.int64(1480),
 np.int64(1490),
 np.int64(1518),
 np.int64(1521),
 np.int64(1603),
 np.int64(1615)]

In [24]:
# cross checking
sorted(Unique_movieid_similar_user)

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(7),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(15),
 np.int64(22),
 np.int64(23),
 np.int64(25),
 np.int64(26),
 np.int64(28),
 np.int64(29),
 np.int64(33),
 np.int64(35),
 np.int64(38),
 np.int64(39),
 np.int64(43),
 np.int64(44),
 np.int64(47),
 np.int64(49),
 np.int64(50),
 np.int64(51),
 np.int64(54),
 np.int64(56),
 np.int64(58),
 np.int64(59),
 np.int64(60),
 np.int64(61),
 np.int64(63),
 np.int64(64),
 np.int64(65),
 np.int64(66),
 np.int64(67),
 np.int64(69),
 np.int64(70),
 np.int64(71),
 np.int64(73),
 np.int64(76),
 np.int64(77),
 np.int64(78),
 np.int64(79),
 np.int64(80),
 np.int64(81),
 np.int64(82),
 np.int64(83),
 np.int64(86),
 np.int64(87),
 np.int64(88),
 np.int64(89),
 np.int64(90),
 np.int64(91),
 np.int64(92),
 np.int64(94),
 np.int64(95),
 np.int64(96),
 np.int64(97),
 np.int64(98),
 np.int64(99),
 np.int64(100),
 np.int64(101),
 np.int64(102),
 np.int64(109),
 np.int64(110),
 np.int64(111),
 np.int64(112),
 np.int64(114),
 np.int64(117),
 np.int64(118),
 np.int64(121),
 np.int64(122),
 np.int64(123),
 np.int64(125),
 np.int64(126),
 np.int64(127),
 np.int64(131),
 np.int64(132),
 np.int64(133),
 np.int64(134),
 np.int64(135),
 np.int64(136),
 np.int64(139),
 np.int64(140),
 np.int64(141),
 np.int64(142),
 np.int64(143),
 np.int64(144),
 np.int64(145),
 np.int64(151),
 np.int64(152),
 np.int64(153),
 np.int64(154),
 np.int64(155),
 np.int64(157),
 np.int64(158),
 np.int64(161),
 np.int64(162),
 np.int64(163),
 np.int64(164),
 np.int64(166),
 np.int64(167),
 np.int64(168),
 np.int64(169),
 np.int64(170),
 np.int64(172),
 np.int64(173),
 np.int64(174),
 np.int64(176),
 np.int64(177),
 np.int64(178),
 np.int64(179),
 np.int64(180),
 np.int64(181),
 np.int64(182),
 np.int64(183),
 np.int64(185),
 np.int64(186),
 np.int64(187),
 np.int64(188),
 np.int64(190),
 np.int64(191),
 np.int64(192),
 np.int64(193),
 np.int64(194),
 np.int64(195),
 np.int64(196),
 np.int64(197),
 np.int64(199),
 np.int64(200),
 np.int64(202),
 np.int64(203),
 np.int64(204),
 np.int64(205),
 np.int64(207),
 np.int64(208),
 np.int64(210),
 np.int64(211),
 np.int64(213),
 np.int64(214),
 np.int64(215),
 np.int64(216),
 np.int64(218),
 np.int64(220),
 np.int64(221),
 np.int64(222),
 np.int64(223),
 np.int64(225),
 np.int64(226),
 np.int64(227),
 np.int64(228),
 np.int64(229),
 np.int64(230),
 np.int64(231),
 np.int64(232),
 np.int64(233),
 np.int64(234),
 np.int64(235),
 np.int64(237),
 np.int64(238),
 np.int64(239),
 np.int64(241),
 np.int64(242),
 np.int64(243),
 np.int64(245),
 np.int64(250),
 np.int64(252),
 np.int64(254),
 np.int64(257),
 np.int64(258),
 np.int64(259),
 np.int64(260),
 np.int64(264),
 np.int64(265),
 np.int64(266),
 np.int64(268),
 np.int64(269),
 np.int64(270),
 np.int64(271),
 np.int64(272),
 np.int64(273),
 np.int64(274),
 np.int64(275),
 np.int64(277),
 np.int64(278),
 np.int64(280),
 np.int64(281),
 np.int64(282),
 np.int64(283),
 np.int64(284),
 np.int64(286),
 np.int64(287),
 np.int64(288),
 np.int64(289),
 np.int64(290),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(300),
 np.int64(301),
 np.int64(302),
 np.int64(304),
 np.int64(305),
 np.int64(307),
 np.int64(308),
 np.int64(309),
 np.int64(310),
 np.int64(311),
 np.int64(312),
 np.int64(313),
 np.int64(315),
 np.int64(316),
 np.int64(318),
 np.int64(319),
 np.int64(321),
 np.int64(322),
 np.int64(323),
 np.int64(324),
 np.int64(326),
 np.int64(328),
 np.int64(329),
 np.int64(332),
 np.int64(336),
 np.int64(338),
 np.int64(340),
 np.int64(343),
 np.int64(345),
 np.int64(347),
 np.int64(354),
 np.int64(356),
 np.int64(357),
 np.int64(358),
 np.int64(366),
 np.int64(367),
 np.int64(371),
 np.int64(372),
 np.int64(373),
 np.int64(378),
 np.int64(380),
 np.int64(381),
 np.int64(382),
 np.int64(383),
 np.int64(384),
 np.int64(385),
 np.int64(386),
 np.int64(387),
 np.int64(388),
 np.int64(389),
 np.int64(392),
 np.int64(393),
 np.int64(395),
 np.int64(396),
 np.int64(399),
 np.int64(400),
 np.int64(401),
 np.int64(402),
 np.int64(403),
 np.int64(405),
 np.int64(407),
 np.int64(408),
 np.int64(414),
 np.int64(415),
 np.int64(416),
 np.int64(417),
 np.int64(418),
 np.int64(419),
 np.int64(421),
 np.int64(422),
 np.int64(423),
 np.int64(427),
 np.int64(428),
 np.int64(430),
 np.int64(431),
 np.int64(432),
 np.int64(433),
 np.int64(434),
 np.int64(435),
 np.int64(443),
 np.int64(448),
 np.int64(451),
 np.int64(455),
 np.int64(457),
 np.int64(462),
 np.int64(465),
 np.int64(467),
 np.int64(468),
 np.int64(469),
 np.int64(470),
 np.int64(471),
 np.int64(472),
 np.int64(473),
 np.int64(474),
 np.int64(476),
 np.int64(477),
 np.int64(478),
 np.int64(479),
 np.int64(480),
 np.int64(481),
 np.int64(482),
 np.int64(483),
 np.int64(484),
 np.int64(485),
 np.int64(487),
 np.int64(488),
 np.int64(489),
 np.int64(490),
 np.int64(491),
 np.int64(492),
 np.int64(493),
 np.int64(494),
 np.int64(495),
 np.int64(496),
 np.int64(497),
 np.int64(498),
 np.int64(499),
 np.int64(500),
 np.int64(501),
 np.int64(502),
 np.int64(503),
 np.int64(504),
 np.int64(505),
 np.int64(506),
 np.int64(507),
 np.int64(509),
 np.int64(510),
 np.int64(511),
 np.int64(514),
 np.int64(515),
 np.int64(516),
 np.int64(518),
 np.int64(519),
 np.int64(520),
 np.int64(521),
 np.int64(523),
 np.int64(525),
 np.int64(526),
 np.int64(527),
 np.int64(528),
 np.int64(530),
 np.int64(535),
 np.int64(546),
 np.int64(549),
 np.int64(550),
 np.int64(553),
 np.int64(557),
 np.int64(558),
 np.int64(559),
 np.int64(561),
 np.int64(566),
 np.int64(568),
 np.int64(570),
 np.int64(571),
 np.int64(582),
 np.int64(583),
 np.int64(584),
 np.int64(588),
 np.int64(589),
 np.int64(591),
 np.int64(597),
 np.int64(601),
 np.int64(602),
 np.int64(603),
 np.int64(604),
 np.int64(606),
 np.int64(607),
 np.int64(608),
 np.int64(609),
 np.int64(610),
 np.int64(611),
 np.int64(612),
 np.int64(613),
 np.int64(614),
 np.int64(616),
 np.int64(618),
 np.int64(619),
 np.int64(620),
 np.int64(622),
 np.int64(627),
 np.int64(628),
 np.int64(629),
 np.int64(630),
 np.int64(631),
 np.int64(632),
 np.int64(633),
 np.int64(637),
 np.int64(642),
 np.int64(647),
 np.int64(648),
 np.int64(650),
 np.int64(651),
 np.int64(654),
 np.int64(655),
 np.int64(657),
 np.int64(659),
 np.int64(660),
 np.int64(661),
 np.int64(662),
 np.int64(663),
 np.int64(671),
 np.int64(673),
 np.int64(678),
 np.int64(679),
 np.int64(680),
 np.int64(681),
 np.int64(685),
 np.int64(686),
 np.int64(687),
 np.int64(689),
 np.int64(690),
 np.int64(692),
 np.int64(693),
 np.int64(696),
 np.int64(699),
 np.int64(700),
 np.int64(702),
 np.int64(704),
 np.int64(705),
 np.int64(707),
 np.int64(708),
 np.int64(709),
 np.int64(710),
 np.int64(712),
 np.int64(713),
 np.int64(714),
 np.int64(715),
 np.int64(716),
 np.int64(717),
 np.int64(722),
 np.int64(723),
 np.int64(724),
 np.int64(725),
 np.int64(727),
 np.int64(728),
 np.int64(729),
 np.int64(731),
 np.int64(732),
 np.int64(734),
 np.int64(735),
 np.int64(736),
 np.int64(739),
 np.int64(741),
 np.int64(742),
 np.int64(747),
 np.int64(748),
 np.int64(749),
 np.int64(750),
 np.int64(751),
 np.int64(754),
 np.int64(756),
 np.int64(761),
 np.int64(762),
 np.int64(765),
 np.int64(771),
 np.int64(774),
 np.int64(775),
 np.int64(776),
 np.int64(778),
 np.int64(781),
 np.int64(783),
 np.int64(785),
 np.int64(790),
 np.int64(792),
 np.int64(794),
 np.int64(795),
 np.int64(801),
 np.int64(807),
 np.int64(812),
 np.int64(815),
 np.int64(820),
 np.int64(821),
 np.int64(823),
 np.int64(825),
 np.int64(826),
 np.int64(827),
 np.int64(832),
 np.int64(837),
 np.int64(840),
 np.int64(841),
 np.int64(842),
 np.int64(845),
 np.int64(846),
 np.int64(847),
 np.int64(865),
 np.int64(866),
 np.int64(869),
 np.int64(873),
 np.int64(878),
 np.int64(879),
 np.int64(892),
 np.int64(895),
 np.int64(898),
 np.int64(899),
 np.int64(900),
 np.int64(901),
 np.int64(902),
 np.int64(904),
 np.int64(905),
 np.int64(908),
 np.int64(921),
 np.int64(923),
 np.int64(926),
 np.int64(928),
 np.int64(930),
 np.int64(934),
 np.int64(936),
 np.int64(939),
 np.int64(940),
 np.int64(942),
 np.int64(951),
 np.int64(956),
 np.int64(965),
 np.int64(966),
 np.int64(967),
 np.int64(968),
 np.int64(969),
 np.int64(988),
 np.int64(990),
 np.int64(991),
 np.int64(1020),
 np.int64(1024),
 np.int64(1028),
 np.int64(1030),
 np.int64(1033),
 np.int64(1036),
 np.int64(1037),
 np.int64(1039),
 np.int64(1041),
 np.int64(1044),
 np.int64(1047),
 np.int64(1048),
 np.int64(1050),
 np.int64(1052),
 np.int64(1053),
 np.int64(1054),
 np.int64(1061),
 np.int64(1091),
 np.int64(1092),
 np.int64(1107),
 np.int64(1112),
 np.int64(1115),
 np.int64(1116),
 np.int64(1119),
 np.int64(1126),
 np.int64(1135),
 np.int64(1140),
 np.int64(1147),
 np.int64(1152),
 np.int64(1153),
 np.int64(1160),
 np.int64(1163),
 np.int64(1172),
 np.int64(1184),
 np.int64(1192),
 np.int64(1197),
 np.int64(1203),
 np.int64(1208),
 np.int64(1212),
 np.int64(1220),
 np.int64(1221),
 np.int64(1222),
 np.int64(1226),
 np.int64(1248),
 np.int64(1249),
 np.int64(1261),
 np.int64(1263),
 np.int64(1269),
 np.int64(1271),
 np.int64(1282),
 np.int64(1284),
 np.int64(1286),
 np.int64(1297),
 np.int64(1303),
 np.int64(1311),
 np.int64(1401),
 np.int64(1402),
 np.int64(1421),
 np.int64(1425),
 np.int64(1435),
 np.int64(1441),
 np.int64(1444),
 np.int64(1446),
 np.int64(1479),
 np.int64(1480),
 np.int64(1490),
 np.int64(1518),
 np.int64(1521),
 np.int64(1603),
 np.int64(1615)]

In [25]:
# Cross Checking
sorted(input_user_watched_movieid)

[np.int64(242),
 np.int64(245),
 np.int64(259),
 np.int64(286),
 np.int64(288),
 np.int64(289),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(310),
 np.int64(312),
 np.int64(324),
 np.int64(329),
 np.int64(332),
 np.int64(690),
 np.int64(898),
 np.int64(899),
 np.int64(990),
 np.int64(991),
 np.int64(1024)]

In [26]:
# Checking the common movie list
list(set(Unique_movieid_similar_user)&set(input_user_watched_movieid))

[np.int64(1024),
 np.int64(898),
 np.int64(259),
 np.int64(899),
 np.int64(286),
 np.int64(288),
 np.int64(289),
 np.int64(292),
 np.int64(294),
 np.int64(299),
 np.int64(690),
 np.int64(310),
 np.int64(312),
 np.int64(324),
 np.int64(329),
 np.int64(332),
 np.int64(990),
 np.int64(991),
 np.int64(242),
 np.int64(245)]

In [27]:
user_pred=pd.DataFrame(user_prediction)
user_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.065326,0.734303,0.629924,1.010669,0.640686,0.476150,1.784569,1.163032,1.513350,0.704478,...,0.394041,0.394434,0.393981,0.392972,0.393344,0.392272,0.394909,0.393590,0.393049,0.392771
1,1.763088,0.384040,0.196179,0.731538,0.225643,0.003892,1.493597,0.876153,1.108467,0.261991,...,-0.086942,-0.085491,-0.087137,-0.088158,-0.087298,-0.089288,-0.087468,-0.088378,-0.086918,-0.086712
2,1.795904,0.329047,0.158829,0.684154,0.173277,-0.035621,1.488230,0.835769,1.135426,0.236383,...,-0.134795,-0.133537,-0.135543,-0.136438,-0.135041,-0.137611,-0.136374,-0.136992,-0.134969,-0.134765
3,1.729951,0.293913,0.127741,0.644932,0.142143,-0.062261,1.437010,0.796249,1.096663,0.211789,...,-0.161413,-0.160220,-0.161542,-0.162586,-0.161634,-0.163877,-0.162283,-0.163080,-0.161442,-0.161248
4,1.796651,0.454474,0.354422,0.763130,0.359539,0.195987,1.547370,0.908904,1.292027,0.437954,...,0.101762,0.102405,0.101923,0.100839,0.101711,0.099951,0.102515,0.101233,0.101075,0.101201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,1.676950,0.346339,0.177518,0.689906,0.199740,0.003297,1.429565,0.830905,1.070986,0.262183,...,-0.092434,-0.091197,-0.092851,-0.093801,-0.092953,-0.094539,-0.092217,-0.093378,-0.092686,-0.092423
939,1.822346,0.419125,0.286430,0.715605,0.294442,0.106633,1.514591,0.853050,1.195304,0.359260,...,0.014060,0.014688,0.014123,0.013060,0.013669,0.011978,0.014065,0.013021,0.013639,0.013796
940,1.591515,0.275269,0.102195,0.624383,0.133762,-0.069553,1.320734,0.765529,1.035088,0.192697,...,-0.166179,-0.164981,-0.166278,-0.167392,-0.166679,-0.168486,-0.166217,-0.167352,-0.166575,-0.166414
941,1.810363,0.404799,0.275450,0.726616,0.281316,0.087068,1.550310,0.850057,1.205745,0.342987,...,-0.008362,-0.007757,-0.008225,-0.009218,-0.008232,-0.010138,-0.008009,-0.009074,-0.008466,-0.008049
942,1.838431,0.479648,0.384963,0.780521,0.388442,0.240998,1.564232,0.946704,1.289865,0.487383,...,0.147027,0.148208,0.147193,0.146199,0.146916,0.145539,0.148194,0.146867,0.146298,0.146415

In [28]:
user_pred_Trans=user_pred.T
user_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.065326,0.734303,0.629924,1.010669,0.640686,0.476150,1.784569,1.163032,1.513350,0.704478,...,0.394041,0.394434,0.393981,0.392972,0.393344,0.392272,0.394909,0.393590,0.393049,0.392771
1,1.763088,0.384040,0.196179,0.731538,0.225643,0.003892,1.493597,0.876153,1.108467,0.261991,...,-0.086942,-0.085491,-0.087137,-0.088158,-0.087298,-0.089288,-0.087468,-0.088378,-0.086918,-0.086712
2,1.795904,0.329047,0.158829,0.684154,0.173277,-0.035621,1.488230,0.835769,1.135426,0.236383,...,-0.134795,-0.133537,-0.135543,-0.136438,-0.135041,-0.137611,-0.136374,-0.136992,-0.134969,-0.134765
3,1.729951,0.293913,0.127741,0.644932,0.142143,-0.062261,1.437010,0.796249,1.096663,0.211789,...,-0.161413,-0.160220,-0.161542,-0.162586,-0.161634,-0.163877,-0.162283,-0.163080,-0.161442,-0.161248
4,1.796651,0.454474,0.354422,0.763130,0.359539,0.195987,1.547370,0.908904,1.292027,0.437954,...,0.101762,0.102405,0.101923,0.100839,0.101711,0.099951,0.102515,0.101233,0.101075,0.101201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,1.676950,0.346339,0.177518,0.689906,0.199740,0.003297,1.429565,0.830905,1.070986,0.262183,...,-0.092434,-0.091197,-0.092851,-0.093801,-0.092953,-0.094539,-0.092217,-0.093378,-0.092686,-0.092423
939,1.822346,0.419125,0.286430,0.715605,0.294442,0.106633,1.514591,0.853050,1.195304,0.359260,...,0.014060,0.014688,0.014123,0.013060,0.013669,0.011978,0.014065,0.013021,0.013639,0.013796
940,1.591515,0.275269,0.102195,0.624383,0.133762,-0.069553,1.320734,0.765529,1.035088,0.192697,...,-0.166179,-0.164981,-0.166278,-0.167392,-0.166679,-0.168486,-0.166217,-0.167352,-0.166575,-0.166414
941,1.810363,0.404799,0.275450,0.726616,0.281316,0.087068,1.550310,0.850057,1.205745,0.342987,...,-0.008362,-0.007757,-0.008225,-0.009218,-0.008232,-0.010138,-0.008009,-0.009074,-0.008466,-0.008049
942,1.838431,0.479648,0.384963,0.780521,0.388442,0.240998,1.564232,0.946704,1.289865,0.487383,...,0.147027,0.148208,0.147193,0.146199,0.146916,0.145539,0.148194,0.146867,0.146298,0.146415

In [29]:
user_pred_Trans[34]

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [30]:
gg=user_pred_Trans[34]

In [31]:
gg

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [32]:
g=pd.DataFrame(gg)

In [33]:
g

            34
0     1.740469
1     0.283366
2     0.114987
3     0.645096
4     0.127844
...        ...
1677 -0.183977
1678 -0.182367
1679 -0.183172
1680 -0.181400
1681 -0.181306

[1682 rows x 1 columns]

In [34]:
s=g.T

In [35]:
s

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
34,1.740469,0.283366,0.114987,0.645096,0.127844,-0.081329,1.448638,0.794313,1.08901,0.194232,...,-0.181256,-0.180156,-0.181837,-0.182819,-0.181432,-0.183977,-0.182367,-0.183172,-0.1814,-0.181306

In [36]:
s[187].values>=0.4

array([ True])

In [37]:
#From recomd list select highest rated flim which would like by the user. Based on User Prediction
highest_Rated=[]
input_user_pre=pd.DataFrame(user_pred_Trans[input_user])
input_user_pred=input_user_pre.T
for re in recom:
    value=input_user_pred[re].values
    if(value>=1):
        highest_Rated.append(re)

In [38]:
len(highest_Rated)

27

In [39]:
#Now we give movieid respective movie list

i_cols=['movie id','movie title','release date','video release date','IMDB URL','unknown','Action','Adventure','Animation',
'Children\'s','Comedy','Crime','Documentry','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']
items=pd.read_csv('ml-100k/u.item',sep='|',names=i_cols,encoding='latin-1')

In [40]:
#Creating movie list based on recom movieid
movie_title=[]
for movieid in highest_Rated:
    mov=items[items['movie id']==movieid]['movie title'].values
    movie_title.append(mov)

In [44]:
movie_title

[array(['Seven (Se7en) (1995)'], dtype=object),
 array(['I.Q. (1994)'], dtype=object),
 array(['Santa Clause, The (1994)'], dtype=object),
 array(['Free Willy (1993)'], dtype=object),
 array(['Sleepless in Seattle (1993)'], dtype=object),
 array(['Aladdin (1992)'], dtype=object),
 array(['Dances with Wolves (1990)'], dtype=object),
 array(['Snow White and the Seven Dwarfs (1937)'], dtype=object),
 array(['Spitfire Grill, The (1996)'], dtype=object),
 array(['Private Benjamin (1980)'], dtype=object),
 array(['Empire Strikes Back, The (1980)'], dtype=object),
 array(['Princess Bride, The (1987)'], dtype=object),
 array(['Apocalypse Now (1979)'], dtype=object),
 array(['GoodFellas (1990)'], dtype=object),
 array(['Henry V (1989)'], dtype=object),
 array(['Sting, The (1973)'], dtype=object),
 array(['Unforgiven (1992)'], dtype=object),
 array(['Field of Dreams (1989)'], dtype=object),
 array(['Breaking the Waves (1996)'], dtype=object),
 array(['Men in Black (1997)'], dtype=object),
 array(['Chasing Amy (1997)'], dtype=object),
 array(['Sense and Sensibility (1995)'], dtype=object),
 array(["Marvin's Room (1996)"], dtype=object),
 array(['In & Out (1997)'], dtype=object),
 array(['Client, The (1994)'], dtype=object),
 array(['Aladdin and the King of Thieves (1996)'], dtype=object),
 array(['Some Like It Hot (1959)'], dtype=object)]

In [45]:
#Converting into pure list
movie_title_list=[]
for m in movie_title:
    print(m)
    mv=list(m)
    movie_title_list.append(mv)

['Seven (Se7en) (1995)']
['I.Q. (1994)']
['Santa Clause, The (1994)']
['Free Willy (1993)']
['Sleepless in Seattle (1993)']
['Aladdin (1992)']
['Dances with Wolves (1990)']
['Snow White and the Seven Dwarfs (1937)']
['Spitfire Grill, The (1996)']
['Private Benjamin (1980)']
['Empire Strikes Back, The (1980)']
['Princess Bride, The (1987)']
['Apocalypse Now (1979)']
['GoodFellas (1990)']
['Henry V (1989)']
['Sting, The (1973)']
['Unforgiven (1992)']
['Field of Dreams (1989)']
['Breaking the Waves (1996)']
['Men in Black (1997)']
['Chasing Amy (1997)']
['Sense and Sensibility (1995)']
["Marvin's Room (1996)"]
['In & Out (1997)']
['Client, The (1994)']
['Aladdin and the King of Thieves (1996)']
['Some Like It Hot (1959)']

In [47]:
#Converting into whole list
import itertools
Final_Recommend_movie=list(itertools.chain.from_iterable(movie_title_list))

In [48]:
Final_Recommend_movie

['Seven (Se7en) (1995)',
 'I.Q. (1994)',
 'Santa Clause, The (1994)',
 'Free Willy (1993)',
 'Sleepless in Seattle (1993)',
 'Aladdin (1992)',
 'Dances with Wolves (1990)',
 'Snow White and the Seven Dwarfs (1937)',
 'Spitfire Grill, The (1996)',
 'Private Benjamin (1980)',
 'Empire Strikes Back, The (1980)',
 'Princess Bride, The (1987)',
 'Apocalypse Now (1979)',
 'GoodFellas (1990)',
 'Henry V (1989)',
 'Sting, The (1973)',
 'Unforgiven (1992)',
 'Field of Dreams (1989)',
 'Breaking the Waves (1996)',
 'Men in Black (1997)',
 'Chasing Amy (1997)',
 'Sense and Sensibility (1995)',
 "Marvin's Room (1996)",
 'In & Out (1997)',
 'Client, The (1994)',
 'Aladdin and the King of Thieves (1996)',
 'Some Like It Hot (1959)']

In [49]:
#Checking the common movie list
list(set(recom)&set(input_user_watched_movieid))

[]

In [78]:
def userbased(input_user,user_similarity,user_predictions,similar_user_count,thres):
    #Convert the user_sim table into DataFrame
    user_sim_table=pd.DataFrame(user_similarity)
    #Find similarity user for 78 using cosine table
    similar_input_user=user_sim_table[input_user].sort_values(ascending=True).head(similar_user_count).index
    #convert into list
    similar_user_input=list(similar_input_user)
    #using similar_user_input, can select movie id from ratings table
    similar_user_movieid_list=[]
    for sim_user in similar_user_input:
        sim=list(ratings[ratings['user_id']==sim_user]['movie_id'])
        similar_user_movieid_list.append(sim)
    #converting as a whole list
    import itertools
    similar_user_movieid_single_list=list(itertools.chain.from_iterable(similar_user_movieid_list))
    #unique movieid from the list
    Unique_movieid_similar_user=set(similar_user_movieid_single_list)
    #input user watched move_list
    input_user_watched_movieid=list(ratings[ratings['user_id']==input_user]['movie_id'].values)
    #create a list which should have recom movieid to the input user
    recom=[]
    for per_id in Unique_movieid_similar_user:
        if(per_id in input_user_watched_movieid):
            pass
        else:
            recom.append(per_id)
    #From recommendation list selecting only highest rated(predictions) value
    highest_Rated=[]
    user_pred=pd.DataFrame(user_predictions)
    user_pred_Trans=user_pred.T
    input_user_pre=pd.DataFrame(user_pred_Trans[input_user])
    input_user_pred=input_user_pre.T
    for re in recom:
        values=input_user_pred[re].values
        if(values>=thres):
            highest_Rated.append(re)
    i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
    items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')
    #Creating Movie List based on recom movieid
    movie_title=[]
    for movieid in highest_Rated:
        move=items[items['movie id']==movieid]['movie title'].values
        movie_title.append(move)
    #converting into pure list
    movie_title_list=[]
    for m in movie_title:
        print(m)
        mv=list(m)
        movie_title_list.append(mv)
    #converting into whole list
    import itertools
    Final_recommend_movie=list(itertools.chain.from_iterable(movie_title_list))
    print("The common Movie in Recom & User:", list(set(recom)&set(input_user_watched_movieid)))
    return Final_recommend_movie

In [80]:
#def userbased(input_user, user_similarity,User_predictions,similar_user_count,similar_user_movieid_count,thres):
Recommended_movie=userbased(34,user_similarity,user_pred,3,1.5)

['I.Q. (1994)']
['Dances with Wolves (1990)']
['Snow White and the Seven Dwarfs (1937)']
['Spitfire Grill, The (1996)']
['Princess Bride, The (1987)']
['Apocalypse Now (1979)']
['Men in Black (1997)']
["Marvin's Room (1996)"]
The common Movie in Recom & User: []

In [63]:
def userbased(input_user,user_similarity,user_predictions,similar_user_count,thres):
    #Convert the user_sim table into DataFrame
    user_sim_table=pd.DataFrame(user_similarity)
    #Find similarity user for 78 using cosine table
    similar_input_user= user_sim_table[input_user].sort_values(ascending=True).head(similar_user_count).index
    #Convert in to list
    similar_user_input=list(similar_input_user) 
    #Using similar_user_input,can select movie id from ratings table
    similar_user_movieid_list=[]
    for sim_user in similar_user_input:
        sim=list(ratings[ratings['user_id']==sim_user]['movie_id'])
        similar_user_movieid_list.append(sim)
    #Converting as a whole list
    import itertools
    similar_user_movieid_single_list=list(itertools.chain.from_iterable(similar_user_movieid_list))
    #Unique movieid from the list
    Unique_movieid_similar_user=set(similar_user_movieid_single_list)
    #Input user watched movie_list
    input_user_watched_movieid=list(ratings[ratings['user_id']==input_user]['movie_id'].values)
    #Create a list which should have recom movieid to the input user
    recom=[]
    for per_id in Unique_movieid_similar_user:
        if(per_id in input_user_watched_movieid):
            pass
        else:
            recom.append(per_id)
    #From recommendation list selecting only hightest rated(predicted) value
    highest_Rated=[]
    user_pred=pd.DataFrame(user_prediction)
    user_pred_Trans=user_pred.T
    input_user_pre=pd.DataFrame(user_pred_Trans[input_user])
    input_user_pred=input_user_pre.T
    for re in recom:
        value=input_user_pred[re].values
        if(value>=thres):
            highest_Rated.append(re)
    i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
    items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')
    #Creating Movie List based on recom movieid
    movie_title=[]
    for movieid in highest_Rated:
        mov=items[items['movie id']==movieid]['movie title'].values
        movie_title.append(mov)
    #Converting into pure list
    movie_title_list=[]
    for m in movie_title:
        print(m)
        mv=list(m)
        movie_title_list.append(mv)
    #Converting into whole list
    import itertools
    Final_Recommend_movie=list(itertools.chain.from_iterable(movie_title_list))
    print("The common Movie in Recom & User:",list(set(recom)&set(input_user_watched_movieid)))
    return Final_Recommend_movie

In [82]:
#def userbased(input_user,user_similarity,user_predictions,similar_user_count,similar_user_movieid_count,thres):
Recommended_movie=userbased(67,user_similarity,user_pred,5,1.5)

['Professional, The (1994)']
['Dances with Wolves (1990)']
['Snow White and the Seven Dwarfs (1937)']
['Princess Bride, The (1987)']
['Apocalypse Now (1979)']
['Men in Black (1997)']
["Marvin's Room (1996)"]
The common Movie in Recom & User: []